from bbsurvival.bb_lib.utils.bb_instance_utils import BBInstanceUtils
from bbsurvival.mod_identity import ModIdentity
from bluuberrylibrary.logs.bb_log_registry import BBLogRegistry
from bluuberrylibrary.utils.debug.bb_injection_utils import BBInjectionUtils
from bluuberrylibrary.utils.instances.bb_situation_utils import BBSituationUtils
from drama_scheduler.drama_node import BaseDramaNode
from event_testing.results import TestResult
from sims4.commands import Command, CommandType
from sims4.resources import Types
from situations.ambient.ambient_service import _AmbientSourceStreet

log = BBLogRegistry().register_log(ModIdentity(), 'bbl_walkbys')
log.enable()


@Command(
    'bbs.print_drama_nodes',
    command_type=CommandType.Live
)
def _bbs_command_print_dramanodes(_connection: int = None):
    from sims4.commands import CheatOutput
    output = CheatOutput(_connection)
    try:
        output(f'Printing Drama Nodes.')
        for (resource_key, instance) in BBInstanceUtils.get_all_instances(Types.DRAMA_NODE, return_type=BaseDramaNode):
            instance: BaseDramaNode = instance
            instance_tuning_name = instance.__name__.lower()
            guid64 = getattr(instance, 'guid64', None)
            log.debug(f'{guid64},  # {instance_tuning_name}')
        output('Done')
    except Exception as ex:
        output('Error occurred.')
        log.error('Problem occurred', exception=ex)


# @BBInjectionUtils.inject(ModIdentity(), Situation, Situation.start_situation.__name__)
def _bbs_disable_walkby_ambient(original, self, *_, **__):
    pass


class BBDramaNodeDisabler:
    DISABLED_DRAMA_NODE_IDS = (
        228039,  # dialogdramanode_university_sportsarena_gamedayreminder_football_arts
        140082,  # festivaldramanode_foodfestival
        231584,  # dialogdramanode_communitycloseness_landgrabpower
        195221,  # dramanode_reputation_bad_caughttakingblood
        280462,  # dramanode_npcinvite_story_progression_childrenstories_adopteddog
        207793,  # pickerdramanode_freelancer_writer_childrens_book
        258435,  # pickerdramanode_career_interiordecorator_room_addition
        194474,  # runaffordancedramanode_actorcareer_auditions_tvhigh_police
        194065,  # dialogdramanode_corporatepartnership_addtrend5
        237855,  # situationdramanode_communitycloseness_introtocivicpolicies
        195211,  # dramanode_reputation_good_happytown
        264792,  # pickerdramanode_career_interiordecorator_level_addition_skill_level_fitness_basement
        211461,  # pickerdramanode_oddjob_stormrepairs
        198199,  # dramanode_actorcareer_performancefeedback_hangten_movie_high
        237857,  # dialogdramanode_communitycloseness_friendcrush
        193812,  # runaffordancedramanode_phone_feudbringer_discussfeud
        233685,  # situationdramanode_communitycloseness_birthdaygift
        297657,  # dialogdramanode_scenario_parentingpredicament_principal_phase2
        199791,  # dialogdramanode_actorcareer_aistaffing_post_gigscheduled_2
        205591,  # islandevents_small_dramanode_townbbq
        339182,  # dialogdramanode_scenario_inheritance_grandma_3a
        257960,  # runaffordancedramanode_freelancer_offergig_interiordecorator
        209014,  # pickerdramanode_oddjob_mahimahi
        198189,  # dramanode_actorcareer_performancefeedback_estellegable_movie_med
        183109,  # holidaydramanode_mainholidays_newyears
        219737,  # pickerdramanode_freelancer_fashion_photographer_formal_wear_3
        195166,  # pickerdramanode_actorcareer_highbudgettv_hopsital
        196009,  # dramanode_npcinvite_date_reputation_good
        283751,  # dramanode_highschool_active_schoolfight
        198211,  # dramanode_actorcareer_performancefeedback_wearereallyhuman_tvlow_high
        261202,  # pickerdramanode_career_interiordecorator_room_renovations_followup_positive
        208029,  # pickerdramanode_freelancer_writer_proofreading_3
        207484,  # pickerdramanode_freelancer_artist_sketch_artist_3
        210099,  # runaffordancedramanode_freelancer_offergig_artist
        234056,  # pickerdramanode_freelancer_maker_craftedcandle_03
        130364,  # dramanode_barnights_knightnight
        129418,  # clubinviterequestdramanode_requestinvite_notinviteonly
        167172,  # dialogdramanode_sp11_intro
        208041,  # pickerdramanode_freelancer_writer_motivational_book_2
        194754,  # dramanode_musicproductionstation_signwithdinkybeats
        194467,  # runaffordancedramanode_actorcareer_auditions_movie_medieval
        198166,  # dramanode_actorcareer_performancefeedback_hangten_commercial_med
        258067,  # dialogdramanode_career_interiordecorator_followup_tv_positive_preshow_sat
        207990,  # pickerdramanode_freelancer_programmer_hack_listerv_2
        125870,  # dramanode_npcinvite_godancing
        199195,  # pickerdramanode_actorcareer_lowbudgettv_western_aistaffing
        261148,  # pickerdramanode_career_interiordecorator_level_renovation_living_kitchen
        233891,  # pickerdramanode_freelancer_maker_tofizz_01
        221716,  # situationdramanode_roommatenpc_whispers
        207790,  # pickerdramanode_freelancer_writer_proofreading
        321829,  # stayoverdramanode_infantintro
        279079,  # dialogdramanode_neighborrelphonecall_followup_romantic_furtherrelationship
        207980,  # pickerdramanode_freelancer_programmer_computer_game_4
        297476,  # dialogdramanode_bestiephonecall_activities
        199217,  # pickerdramanode_actorcareer_lowbudgettv_houselow_wellsuited
        279978,  # dialogdramanode_hsteam_switch_computerteam
        237670,  # pickerdramanode_freelancer_batuu_resistance_repeatable_01
        195397,  # runaffordancedramanode_actorcareer_agency_wearereallyhuman_offergig
        228547,  # collegeorganizationevents_barnight_party_wednesday
        198178,  # dramanode_actorcareer_performancefeedback_estellegable_commercial_high
        127431,  # dramanode_npcinvite_godancing_chalet
        239414,  # pickerdramanode_freelancer_batuu_resistance_repeatable_05
        282945,  # dialogdramanode_hsprom_lockerinvite_failure
        200710,  # npcinvite_dramanode_situation_reputation_charity
        195149,  # pickerdramanode_actorcareer_commercial_hospital
        281032,  # dramanode_highschool_active_calendar_exam
        143042,  # npcinvite_cityinvites_festivals_fleamarket_haggle
        260762,  # pickerdramanode_career_interiordecorator_room_addition_skill_room_piano
        155681,  # npcinvite_cityinvites_festivals_buyashirt_logic
        149398,  # npcinvite_cityinvites_festivals_food_trychopsticksfoods
        268626,  # dramanode_mayor_jam
        244458,  # pickerdramanode_freelancer_batuu_firstorder_repeatable_13
        283430,  # dialogdramanode_openablewindow_schoolgame
        193123,  # dramanode_reputation_good_friends
        195171,  # pickerdramanode_actorcareer_film_victorian
        134434,  # dramanode_npcinvite_restaurant_enemydate
        208032,  # pickerdramanode_freelancer_writer_marketing_copy_3
        138192,  # dramanode_npcinvite_restaurant_standarddate_firstweek
        202834,  # dramanode_reputation_bad_addnewfriend_child
        125667,  # dialogdramanode_congratsonengagement
        134325,  # dramanode_npcinvite_restaurant_standard
        125790,  # dialogdramanode_goingoutsocials_offlot_matchmake_fail
        164723,  # runaffordancedramanode_phone_chat_acquiredfamilyrelbit
        262502,  # pickerdramanode_villagerhelp_foodforage_short_crittertender
        207543,  # pickerdramanode_freelancer_artist_public_artist_2
        143028,  # npcinvite_cityinvites_festivals_blossom_drinktea
        195418,  # runaffordancedramanode_actorcareer_agency_seriousbusiness_offergig
        218351,  # dramanode_npcinvite_magicduel_challenge
        260880,  # pickerdramanode_career_interiordecorator_level_renovation_kitchen
        198203,  # dramanode_actorcareer_performancefeedback_seriousbusiness_tvhigh_low
        216073,  # pickerdramanode_freelancer_fashion_photographer_backgrounds
        244214,  # pickerdramanode_freelancer_batuu_firstorder_repeatable_02
        207444,  # pickerdramanode_freelancer_artist_art_teacher
        199212,  # pickerdramanode_actorcareer_highbudgettv_hopsital_wellsuited
        234027,  # pickerdramanode_freelancer_maker_jarcandles_02
        296656,  # dialogdramanode_scenario_stuckintheirshadow_3aliensecret
        202884,  # dramanode_reputation_good_career_actor
        263016,  # pickerdramanode_villagerhelp_narrative_agnescrumplebottom_2
        263186,  # pickerdramanode_villagerhelp_livestockgardenlong_agathacrumplebottom
        199234,  # pickerdramanode_actorcareer_film_pirate_gran
        211276,  # pickerdramanode_oddjob_fooddelivery
        233383,  # pickerdramanode_freelancer_maker_rug_03
        301763,  # dialogdramanode_scenario_newintown_phase4_newacquaintancecaller_friendgym
        258361,  # dialogdramanode_career_interiordecorator_followup_tv_negative_preshow_wed
        143049,  # npcinvite_cityinvites_festivals_food_sample
        260755,  # pickerdramanode_career_interiordecorator_room_addition_skill_room_guitar
        222023,  # pickerdramanode_freelancer_fashion_photographer_style_3
        231573,  # dialogdramanode_communitycloseness_thesimulation
        308150,  # dialogdramanode_jobloss_layoff_mailedgift
        259969,  # festivalcontestdramanode_villagefair_cowmilk
        308848,  # dialogdramanode_jobloss_joboffer_astronaut
        208039,  # pickerdramanode_freelancer_writer_childrens_book_2
        216022,  # pickerdramanode_freelancer_fashion_photographer_formal_wear
        239187,  # situationdramanode_communitycloseness_randomgift_makernpc
        207651,  # pickerdramanode_freelancer_programmer_mod_game
        259237,  # pickerdramanode_career_interiordecorator_room_addition_skill_room_painting
        235712,  # situationdramanode_repo_situation_billsdelinquent
        199061,  # situation_dramanode_famevisit
        125785,  # dialogdramanode_goingoutsocials_offlot_breakupsims
        199183,  # pickerdramanode_actorcareer_film_western_aistaffing
        143035,  # npcinvite_cityinvites_venueinvites_gym
        199794,  # dialogdramanode_actorcareer_aistaffing_post_gigscheduled_5
        309233,  # stayoverdramanode_mopeyvisit
        125737,  # dialogdramanode_happybirthday
        211464,  # pickerdramanode_oddjob_wedding
        198192,  # dramanode_actorcareer_performancefeedback_hangten_tvlow_med
        225718,  # situationdramanode_universitygraduation_science
        224376,  # collegeorganizations_dramanodes_events_debate_showdown
        199205,  # pickerdramanode_actorcareer_film_medieval_wellsuited
        224238,  # dialogdramanode_university_caughtcheating_homework
        205594,  # islandevents_small_dramanode_flowersandmusic
        279974,  # dialogdramanode_hsteam_switch_chessteam
        339177,  # dialogdramanode_scenario_inheritance_grandma_1b_talk
        209017,  # pickerdramanode_oddjob_woodworking
        268602,  # dialogdramanode_villagerhelp_discoverytracker_offerhelp_day1
        281849,  # highschoolfestival_sportsday_football
        258358,  # dialogdramanode_career_interiordecorator_followup_tv_negative_preshow_sun
        195609,  # dramanode_reputation_good_career_entertainer
        283432,  # dialogdramanode_openablewindow_popconcert
        260553,  # pickerdramanode_career_interiordecorator_room_addition_skill_room_fitness
        227350,  # dialogdramanode_scholarshipinfo
        231580,  # dialogdramanode_communitycloseness_telemarketer
        308910,  # dialogdramanode_jobloss_joboffer_writer
        199281,  # dialogdramanode_actorcareer_gran_auditionfail
        241543,  # pickerdramanode_freelancer_batuu_firstorder_story_mission_6
        198060,  # tutorialdramanode
        298602,  # dialogdramanode_scenario_newintown_phase5_intro
        126021,  # dialogdramanode_newenemy
        234055,  # pickerdramanode_freelancer_maker_craftedcandle_02
        273858,  # dialogdramanode_gotthejob
        140084,  # festivaldramanode_lampfestival
        223142,  # collegeorganizations_events_schoolspirit_prank_gamedayparty
        235567,  # situationdramanode_communitycloseness_randomgift_championofthepeople
        262232,  # pickerdramanode_villagerhelp_groceryowner
        241681,  # pickerdramanode_freelancer_batuu_firstorder_story_mission_7
        183094,  # dramanode_premadeholiday_surprise_pirateday
        258888,  # pickerdramanode_career_interiordecorator_level_renovation
        194476,  # runaffordancedramanode_actorcareer_auditions_tvlow_kids
        198163,  # dramanode_actorcareer_performancefeedback_wearereallyhuman_commercial_low
        125687,  # dialogdramanode_congratsonmarriage
        258068,  # dialogdramanode_career_interiordecorator_followup_tv_positive_preshow_sun
        263107,  # pickerdramanode_career_interiordecorator_room_renovations_bedroom
        194067,  # dialogdramanode_corporatepartnership_addtrend2
        195213,  # dramanode_reputation_bad_pickpocket
        193028,  # runaffordancedramanode_actorcareer_auditions_commercial_pirate
        199172,  # pickerdramanode_actorcareer_commercial_hospital_aistaffing
        227733,  # collegeorganizationevents_barnight_party_sunday
        230262,  # dialogdramanode_university_enrollmentinfo_permanentcooldown
        219799,  # pickerdramanode_freelancer_fashion_photographer_backgrounds_2
        221721,  # dialogdramanode_roommatenpc_lockedout_call
        211463,  # pickerdramanode_oddjob_underwaterpictures
        282124,  # dialogdramanode_hsexit_graduateearly
        207985,  # pickerdramanode_freelancer_programmer_encryption_3
        207493,  # pickerdramanode_freelancer_artist_art_teacher_2
        219773,  # pickerdramanode_freelancer_fashion_photographer_poses_3
        274689,  # dramanode_npcinvite_discussexpandingthefamily_hadbaby_targetsim
        241945,  # pickerdramanode_freelancer_batuu_resistance_story_03
        199226,  # pickerdramanode_actorcareer_commercial_hospital_gran
        207547,  # pickerdramanode_freelancer_artist_splash_art_3
        209008,  # pickerdramanode_oddjob_beachcomb_seashells
        198191,  # dramanode_actorcareer_performancefeedback_hangten_tvlow_low
        207448,  # pickerdramanode_freelancer_artist_portrait
        183107,  # holidaydramanode_mainholidays_winterfest
        199248,  # pickerdramanode_actorcareer_lowbudgettv_kids_gran
        234047,  # pickerdramanode_freelancer_maker_carvedcandle_02
        208031,  # pickerdramanode_freelancer_writer_marketing_copy_4
        198213,  # dramanode_actorcareer_performancefeedback_wearereallyhuman_tvhigh_med
        267372,  # pickerdramanode_career_interiordecorator_level_renovation_high
        278854,  # situationdramanode_npcrelationshipautonomy_breakupwith
        195636,  # dramanode_reputation_good_career_writer
        208053,  # pickerdramanode_freelancer_writer_mystery_3
        223016,  # collegeorganizations_dramanodes_events_paintininthepark_sunday
        125807,  # dialogdramanode_welcometoclub
        262485,  # pickerdramanode_villagerhelp_livestockshort_grocerydelivery
        198713,  # runaffordancedramanode_actorcareer_agency_wearereallyhuman_offergig_tutorial
        283689,  # dramanode_highschool_active_debug_schoolfight
        226220,  # venueeventdramanode_university_studentcommons_arts_debatepractice_tues
        270375,  # dialogdramanode_requiredingredients_starving
        194756,  # dramanode_musicproductionstation_signwithmaxismusicmachine
        208043,  # pickerdramanode_freelancer_writer_non_fiction_2
        183089,  # dramanode_premadeholiday_surprise_battleroyale
        194469,  # runaffordancedramanode_actorcareer_auditions_movie_superhero
        140065,  # dramanode_npcinvite_criticcareer_localhangout_restaurant
        125787,  # clubinvitedramanode_joinclubfriend
        221714,  # situationdramanode_roommatenpc_argument
        222057,  # venueeventdramanode_university_studentcommons_science_mixer
        207982,  # pickerdramanode_freelancer_programmer_computer_game_3
        199219,  # pickerdramanode_actorcareer_lowbudgettv_kids_wellsuited
        279976,  # dialogdramanode_hsteam_switch_footballteam
        207538,  # pickerdramanode_freelancer_artist_logo_design_3
        216076,  # pickerdramanode_freelancer_fashion_photographer_style
        198180,  # dramanode_actorcareer_performancefeedback_seriousbusiness_commercial_high
        127429,  # dramanode_npcinvite_godancing_ruins
        241930,  # pickerdramanode_freelancer_batuu_scoundrel_story_06
        195740,  # dramanode_reputation_good_newfriendintro
        199209,  # pickerdramanode_actorcareer_film_western_wellsuited
        207528,  # pickerdramanode_freelancer_artist_environment_concept_2
        234022,  # pickerdramanode_freelancer_maker_tofizz_03
        195607,  # dramanode_reputation_good_career_business
        267365,  # pickerdramanode_career_interiordecorator_level_addition_high
        246532,  # festivaldramanodes_lightfestival
        195151,  # pickerdramanode_actorcareer_commercial_western
        199247,  # pickerdramanode_actorcareer_lowbudgettv_housenice_gran
        263189,  # pickerdramanode_villagerhelp_livestockgardenlong_grocerydelivery
        231577,  # dialogdramanode_communitycloseness_familymatters
        283656,  # dramanode_highschool_active_debug_firedrill
        143044,  # npcinvite_cityinvites_festivals_food_buyingredients
        223009,  # collegeorganization_dramanodes_events_secretsociety_ritual
        262492,  # pickerdramanode_villagerhelp_wildanimalshort_crittertender
        195173,  # pickerdramanode_actorcareer_film_medieval
        214869,  # pickerdramanode_freelancer_fashion_photographer_sleep_wear
        142806,  # dramanode_cityinvites_rabbithole_opera
        259972,  # festivalcontestdramanode_villagefair_normalcroppie
        258328,  # dialogdramanode_career_interiordecorator_followup_clientcall_note_negative
        228261,  # dialogdramanode_lawcareer_judge_bribe
        308501,  # stayoverdramanode_clone
        183096,  # dramanode_premadeholiday_surprise_lottery
        127387,  # dramanode_barnights_guysnight
        202836,  # dramanode_reputation_bad_newfriendintro_child
        199186,  # pickerdramanode_actorcareer_highbudgettv_hopsital_aistaffing
        226464,  # collegeorganizationevents_barnight_robotics
        258441,  # dialogdramanode_career_interiordecorator_followup_clientcall_note_positive
        207973,  # pickerdramanode_freelancer_programmer_website_3
        134420,  # dramanode_npcinvite_restaurant_congratsonthepromotion
        199176,  # pickerdramanode_actorcareer_commercial_western_aistaffing
        143030,  # npcinvite_cityinvites_festivals_food_eatspicy
        298531,  # dialogdramanode_scenario_parentingpredicament_principal_phase4_teenager
        195420,  # runaffordancedramanode_actorcareer_agency_estellegable_offergig
        216075,  # pickerdramanode_freelancer_fashion_photographer_poses
        198205,  # dramanode_actorcareer_performancefeedback_seriousbusiness_tvhigh_high
        317780,  # situationdramanode_familytrope_sundayvisit
        207446,  # pickerdramanode_freelancer_artist_character_concept
        241933,  # pickerdramanode_freelancer_batuu_scoundrel_story_09
        199214,  # pickerdramanode_actorcareer_highbudgettv_victorian_wellsuited
        195442,  # dialogdramanode_quirk_publicnumber_embarrassed
        202886,  # dramanode_reputation_good_career_styleinfluencer
        281854,  # highschoolfestival_sciencefair_computer
        137944,  # dramanode_npcinvite_criticcareer_localhangout_club
        199236,  # pickerdramanode_actorcareer_film_victorian_gran
        125714,  # dialogdramanode_condolencesfordeath
        236676,  # dialogdramanode_entrepreneur_med
        143051,  # npcinvite_cityinvites_festivals_lamp_drinktea
        198217,  # dramanode_actorcareer_performancefeedback_wearereallyhuman_movie_high
        234035,  # pickerdramanode_freelancer_maker_sofa_03
        262491,  # pickerdramanode_villagerhelp_gardenshort_agathacrumplebottom
        194461,  # runaffordancedramanode_actorcareer_auditions_commercial_housenice
        231579,  # dialogdramanode_communitycloseness_prankcall
        198711,  # runaffordancedramanode_actorcareer_agency_hangten_offergig_tutorial
        289611,  # dialogdramanode_werewolfpack_alliancefeud
        259971,  # festivalcontestdramanode_villagefair_chickenegg
        226463,  # collegeorganizationevents_barnight_debatesociety
        228042,  # dialogdramanode_university_sportsarena_gamedayreminder_esports_science
        234050,  # pickerdramanode_freelancer_maker_kidbed_01
        263200,  # pickerdramanode_villagerhelp_socialmedium_grocerydelivery
        195216,  # dramanode_reputation_bad_caughtstealing
        279011,  # venueeventdramanode_thriftstore_openmic_poetry
        267246,  # pickerdramanode_career_interiordecorator_level_renovation_commercial_vet_clinic
        280767,  # preprominvitedramanode
        280459,  # dramanode_npcinvite_story_progression_childrenstories_hadbaby
        196075,  # dramanode_reputation_bad_newfriendintro
        283685,  # dramanode_highschool_active_debug_careerday
        295441,  # dialogdramanode_scenario_stuckintheirshadow_3rival_fired
        207653,  # pickerdramanode_freelancer_programmer_virus
        194473,  # runaffordancedramanode_actorcareer_auditions_tvhigh_hospital
        302204,  # dialogdramanode_scenario_stuckintheirshadow_rival_4aalienpet
        263108,  # pickerdramanode_career_interiordecorator_room_renovations_bathroom
        143037,  # npcinvite_cityinvites_venueinvites_park
        199796,  # dialogdramanode_actorcareer_aistaffing_post_gigscheduled_7
        155260,  # dramanode_vampires_initial_vampireintroduction
        268120,  # pickerdramanode_villagerhelp_socialmedium_agnescrumplebottom
        258428,  # pickerdramanode_career_interiordecorator_room_renovation
        211466,  # pickerdramanode_oddjob_datingguru
        198194,  # dramanode_actorcareer_performancefeedback_hangten_tvhigh_low
        237858,  # dialogdramanode_communitycloseness_parentcheckin
        233686,  # situationdramanode_communitycloseness_trashhelp
        261504,  # pickerdramanode_villagerhelp_socialshort_grocerydelivery
        199207,  # pickerdramanode_actorcareer_film_superhero_wellsuited
        297841,  # dialogdramanode_scenario_stuckintheirshadow_1managercall
        339179,  # dialogdramanode_scenario_inheritance_grandma_2b_job
        299210,  # dialogdramanode_socialmediaposttns
        207526,  # pickerdramanode_freelancer_artist_character_concept_3
        209019,  # pickerdramanode_oddjob_catchfrogs
        124496,  # dramanode_npcinvite_birthdayparty
        198184,  # dramanode_actorcareer_performancefeedback_estellegable_tvlow_high
        183110,  # holidaydramanode_mainholidays_harvestfest
        195165,  # pickerdramanode_actorcareer_highbudgettv_police
        234042,  # pickerdramanode_freelancer_maker_floorlight_01
        195611,  # dramanode_reputation_good_career_painter
        296655,  # dialogdramanode_scenario_stuckintheirshadow_3inviteorkick
        261201,  # pickerdramanode_career_interiordecorator_room_renovations_followup_referred
        308908,  # dialogdramanode_jobloss_joboffer_styleinfluencer
        279912,  # graduationvenueeventdramanode_graduation
        241102,  # pickerdramanode_freelancer_batuu_firstorder_story_mission_3
        127274,  # dramanode_npcinvite_flirtytext
        243876,  # pickerdramanode_freelancer_batuu_scoundrel_15
        300652,  # dialogdramanode_scenario_stuckintheirshadow_4apostcard
        195633,  # dramanode_reputation_good_career_techguru
        273860,  # dialogdramanode_askifpromotion
        231588,  # dialogdramanode_communitycloseness_hotheaded
        142869,  # dramanode_cityinvites_rabbithole_circus
        222042,  # venueeventdramanode_university_studentcommons_arts_mixer
        267666,  # pickerdramanode_career_interiordecorator_level_renovation_living
        227056,  # venueeventdramanode_university_studentcommons_science_robotbuilding_tuesday
        262234,  # pickerdramanode_villagerhelp_pubowner
        207797,  # pickerdramanode_freelancer_writer_science_fiction
        183092,  # dramanode_premadeholiday_surprise_skillday
        194478,  # runaffordancedramanode_actorcareer_auditions_tvlow_pirate
        198165,  # dramanode_actorcareer_performancefeedback_estellegable_commercial_med
        194069,  # dialogdramanode_corporatepartnership_addtrend4
        202840,  # dramanode_reputation_good_newfriendintro_child
        195215,  # dramanode_reputation_bad_caughtcheating
        265012,  # festivalcontestsubdramanode_villagefair_wool
        207987,  # pickerdramanode_freelancer_programmer_encryption_2
        208406,  # situationdramanode_islanderculture_deathcomfort
        199174,  # pickerdramanode_actorcareer_commercial_kids_aistaffing
        164890,  # dialogdramanode_familygift
        207495,  # pickerdramanode_freelancer_artist_art_teacher_3
        211457,  # pickerdramanode_oddjob_bonsai
        258060,  # dialogdramanode_career_interiordecorator_followup_tv_cleanup
        202591,  # dialogdramanode_quirk_publicnumber_flirty_t2t
        207977,  # pickerdramanode_freelancer_programmer_mobile_app_4
        241951,  # pickerdramanode_freelancer_batuu_resistance_story_09
        199228,  # pickerdramanode_actorcareer_commercial_kids_gran
        274844,  # dialogdramanode_asksimtopursuedreamjob_changecareer
        209010,  # pickerdramanode_oddjob_cave
        207450,  # pickerdramanode_freelancer_artist_forgery
        195154,  # pickerdramanode_actorcareer_lowbudgettv_housenice
        199250,  # pickerdramanode_actorcareer_lowbudgettv_western_gran
        125724,  # dialogdramanode_gotnewjob
        198215,  # dramanode_actorcareer_performancefeedback_wearereallyhuman_movie_low
        267374,  # pickerdramanode_career_interiordecorator_room_addition_high
        278852,  # situationdramanode_npcrelationshipautonomy_asktoprom
        308903,  # dialogdramanode_jobloss_joboffer_entertainer
        199240,  # pickerdramanode_actorcareer_highbudgettv_hopsital_gran
        301769,  # dialogdramanode_scenario_newintown_phase4_newacquaintancecaller_friendbar
        184953,  # dialogdramanode_surpriseholiday_lottery_wininvite
        208055,  # pickerdramanode_freelancer_writer_biography_2
        224401,  # situationdramanode_repo_situation
        234060,  # pickerdramanode_freelancer_maker_finewalldecor_03
        261392,  # pickerdramanode_career_interiordecorator_level_renovation_sponsored_library
        255199,  # dialogdramanode_career_interiordecorator_followup_clientcall_referred
        134439,  # dramanode_npcinvite_restaurant_standarddate
        241370,  # pickerdramanode_freelancer_batuu_firstorder_story_mission_5
        211433,  # pickerdramanode_oddjob_lawnmowing
        205654,  # islandevents_large_dramanode_islandcelebration
        208045,  # pickerdramanode_freelancer_writer_non_fiction_4
        194471,  # runaffordancedramanode_actorcareer_auditions_tvhigh_western
        127263,  # dramanode_npcinvite_playfultext
        219800,  # pickerdramanode_freelancer_fashion_photographer_lights_2
        197151,  # loungevenueevents_openmic_saturday
        199199,  # pickerdramanode_actorcareer_commercial_housenice_wellsuited
        207657,  # pickerdramanode_freelancer_programmer_encryption
        199221,  # pickerdramanode_actorcareer_lowbudgettv_western_wellsuited
        199800,  # dialogdramanode_actorcareer_aistaffing_post_gignotscheduled_4
        195125,  # pickerdramanode_actorcareer_commercial_pirate
        227625,  # collegeorganizations_dramanodes_events_paintininthepark_thursday
        195417,  # runaffordancedramanode_actorcareer_agency_hangten_offergig
        260456,  # dialogdramanode_career_interiordecorator_followup_clientcall_returning_positive_postinvite
        207540,  # pickerdramanode_freelancer_artist_portrait_2
        198182,  # dramanode_actorcareer_performancefeedback_estellegable_tvlow_low
        241928,  # pickerdramanode_freelancer_batuu_scoundrel_story_04
        199211,  # pickerdramanode_actorcareer_highbudgettv_apocalypse_wellsuited
        264719,  # dialogdramanode_freesimoleons
        283646,  # dialogdramanode_moveout
        202592,  # dialogdramanode_quirk_publicnumber_happy_t2t
        246534,  # festivaldramanodes_snowfestival
        199233,  # pickerdramanode_actorcareer_film_medieval_gran
        165263,  # dramanode_phone_npcinvite_family
        143046,  # npcinvite_cityinvites_festivals_food_discusslocalcuisine
        236675,  # dialogdramanode_entrepreneur_low
        231574,  # dialogdramanode_communitycloseness_gogreen
        195175,  # pickerdramanode_actorcareer_film_western
        267253,  # pickerdramanode_career_interiordecorator_level_addition_famous_high_fame
        280464,  # dramanode_npcinvite_story_progression_childrenstories_adoptedtoddler
        266522,  # pickerdramanode_career_interiordecorator_room_addition_inlaw_unit
        258330,  # dialogdramanode_career_interiordecorator_followup_clientcall_returning_negative
        208036,  # pickerdramanode_freelancer_writer_clickbait_article_3
        268047,  # pickerdramanode_villagerhelp_livestockgardenlong_mayor
        268612,  # dialogdramanode_villagerhelp_discoverytracker_offerhelp_day3_simtns
        127385,  # dramanode_barnights_ladiesnight
        202838,  # dramanode_reputation_good_addnewfriend_child
        207648,  # pickerdramanode_freelancer_programmer_spreadsheet_setup
        199188,  # pickerdramanode_actorcareer_highbudgettv_victorian_aistaffing
        262230,  # pickerdramanode_villagerhelp_crittertender
        258050,  # dialogdramanode_career_interiordecorator_followup_tv_positive_preshow_mon
        134418,  # dramanode_npcinvite_restaurant_burythehatchet
        207975,  # pickerdramanode_freelancer_programmer_mobile_app_2
        149699,  # npcinvite_cityinvites_festivals_lamp_lightfireworks
        143032,  # npcinvite_cityinvites_festivals_logic_participateincontest
        199793,  # dialogdramanode_actorcareer_aistaffing_post_gigscheduled_4
        199178,  # pickerdramanode_actorcareer_film_dancingintherain_aistaffing
        309234,  # stayoverdramanode_disaster
        339184,  # dialogdramanode_scenario_inheritance_grandma_3b
        211469,  # pickerdramanode_oddjob_furnituremoving
        198207,  # dramanode_actorcareer_performancefeedback_seriousbusiness_movie_med
        279080,  # dialogdramanode_neighborrelphonecall_followup_romantic_nofurtherrelationship
        199200,  # pickerdramanode_actorcareer_commercial_kids_wellsuited
        227676,  # collegeorganizationevents_studygroup_library_thursday
        195444,  # dialogdramanode_quirk_publicnumber_inspired
        296660,  # dialogdramanode_scenario_stuckintheirshadow_4bspaceprint
        268607,  # dialogdramanode_villagerhelp_discoverytracker_offerhelp_day1_villagertns
        235042,  # situationdramanode_trashupdate_wastemanager
        281852,  # highschoolfestival_sportsday_cheer
        234033,  # pickerdramanode_freelancer_maker_sofa_01
        154435,  # dialogdramanode_introtovampire_call2
        258357,  # dialogdramanode_career_interiordecorator_followup_tv_negative_preshow_sat
        143053,  # npcinvite_cityinvites_festivals_lamp_watchfireworks
        322365,  # dialogdramanode_familybirthdaygift
        336484,  # dialogdramanode_freesimoleons2
        194463,  # runaffordancedramanode_actorcareer_auditions_commercial_kids
        219711,  # pickerdramanode_freelancer_fashion_photographer_athletic_wear_2
        281031,  # dramanode_highschool_active_calendar_careerday
        187443,  # dialogdramanode_sendforgedbreakupletter_brokenup
        124702,  # runaffordancedramanode_phone_chat
        142815,  # npcinvite_cityinvites_apartmentinvites_fromfriend
        125946,  # dramanode_npcinvite_playhooky
        165280,  # dramanode_phone_npcinvite_family_venue
        198135,  # dramanode_actorcareer_performancefeedback_estellegable_commercial_low
        297045,  # dialogdramanode_scenario_newintown_phase3aintro
        226461,  # collegeorganizationevents_barnight_honorsociety
        228040,  # dialogdramanode_university_sportsarena_gamedayreminder_football_science
        234048,  # pickerdramanode_freelancer_maker_carvedcandle_03
        231587,  # dialogdramanode_communitycloseness_themotivegames
        263202,  # pickerdramanode_villagerhelp_socialmedium_mayor
        195218,  # dramanode_reputation_bad_despised
        280461,  # dramanode_npcinvite_story_progression_childrenstories_adoptedcat
        127241,  # dramanode_npcinvite_happytext
        207655,  # pickerdramanode_freelancer_programmer_mobile_app
        274507,  # dialogdramanode_goingoutsocials_offlot_matchmake_fail
        207792,  # pickerdramanode_freelancer_writer_clickbait_article
        294373,  # dialogdramanode_scenario_parentingpredicament_principal_phase1
        194475,  # runaffordancedramanode_actorcareer_auditions_tvhigh_apocalypse
        221592,  # venueeventdramanode_university_studentcommons_science_esports
        265007,  # festivalcontestsubdramanode_villagefair_egg
        125789,  # dialogdramanode_goingoutsocials_offlot_matchmake_success
        143039,  # npcinvite_cityinvites_festivals_blossom_paint
        199798,  # dialogdramanode_actorcareer_aistaffing_post_gignotscheduled_2
        222417,  # situationdramanode_collegeorganization_secretsociety_joinvisit
        266622,  # pickerdramanode_career_interiordecorator_room_renovations_office
        208991,  # situationdramanode_islanderculture_extrafood
        198196,  # dramanode_actorcareer_performancefeedback_hangten_tvhigh_high
        211460,  # pickerdramanode_oddjob_steal
        237856,  # dialogdramanode_communitycloseness_siblingsimtock
        129583,  # dialogdramanode_test_node
        233684,  # situationdramanode_communitycloseness_randomgift
        241946,  # pickerdramanode_freelancer_batuu_resistance_story_04
        199788,  # dialogdramanode_actorcareer_aistaffing_post_generic2
        309231,  # stayoverdramanode_parentalhelp
        339181,  # dialogdramanode_scenario_inheritance_grandma_2d_burninheritance
        207544,  # pickerdramanode_freelancer_artist_public_artist_3
        239251,  # pickerdramanode_freelancer_batuu_scoundrel_story_01
        209013,  # pickerdramanode_oddjob_kava
        198186,  # dramanode_actorcareer_performancefeedback_estellegable_tvhigh_med
        183108,  # holidaydramanode_mainholidays_loveday
        243915,  # pickerdramanode_freelancer_batuu_scoundrel_4
        261819,  # pickerdramanode_career_interiordecorator_level_renovation_commercial_lounge
        195167,  # pickerdramanode_actorcareer_highbudgettv_victorian
        234040,  # pickerdramanode_freelancer_maker_kombucha_03
        154436,  # dialogdramanode_introtovampire_call3
        208028,  # pickerdramanode_freelancer_writer_proofreading_2
        198208,  # dramanode_actorcareer_performancefeedback_seriousbusiness_movie_high
        261203,  # pickerdramanode_career_interiordecorator_room_renovations_followup_negative
        207483,  # pickerdramanode_freelancer_artist_sketch_artist_2
        224755,  # collegeorganizations_dramanodes_events_schoolspirit_party_gamedayparty
        208050,  # pickerdramanode_freelancer_writer_science_fiction_3
        210098,  # runaffordancedramanode_freelancer_offergig_writer
        234059,  # pickerdramanode_freelancer_maker_finewalldecor_02
        241252,  # pickerdramanode_freelancer_batuu_firstorder_story_mission_4
        142871,  # dramanode_cityinvites_rabbithole_theater
        125893,  # dramanode_npcinvite_celebratepromotion
        196252,  # dramanode_reputation_good_donatedtocharity
        194755,  # dramanode_musicproductionstation_signwithnewtastemakers
        207799,  # pickerdramanode_freelancer_writer_biography
        183090,  # dramanode_premadeholiday_surprise_tvpremiere
        194464,  # runaffordancedramanode_actorcareer_auditions_commercial_western
        198167,  # dramanode_actorcareer_performancefeedback_seriousbusiness_commercial_med
        258064,  # dialogdramanode_career_interiordecorator_followup_tv_positive_preshow_wed
        265014,  # festivalcontestsubdramanode_villagefair_milk
        240205,  # pickerdramanode_freelancer_batuu_scoundrel_3
        239862,  # pickerdramanode_freelancer_batuu_firstorder_story_mission_2
        267658,  # pickerdramanode_career_interiordecorator_level_addition_mancave
        239468,  # pickerdramanode_freelancer_batuu_resistance_repeatable_15
        199192,  # pickerdramanode_actorcareer_lowbudgettv_housenice_aistaffing
        197144,  # loungevenueevents_openmic_friday
        239631,  # pickerdramanode_freelancer_batuu_firstorder_intro_mission
        221717,  # situationdramanode_roommatenpc_wooing
        198598,  # npcinvite_loungeevent_meetacelebrity
        211459,  # pickerdramanode_oddjob_seajet
        274247,  # dialogdramanode_discussexpandingthefamily_impregnant_targetsim
        279078,  # dialogdramanode_neighborrelphonecall_initial_romantic
        297477,  # dialogdramanode_bestiephonecall_trendi
        241949,  # pickerdramanode_freelancer_batuu_resistance_story_07
        266369,  # pickerdramanode_career_interiordecorator_room_renovations_sponsored_gym
        199230,  # pickerdramanode_actorcareer_commercial_western_gran
        198179,  # dramanode_actorcareer_performancefeedback_hangten_commercial_high
        207452,  # pickerdramanode_freelancer_artist_icons
        152037,  # dramanode_vampirecreation_invitetotransform_hashome
        195156,  # pickerdramanode_actorcareer_lowbudgettv_houselow
        266367,  # pickerdramanode_career_interiordecorator_level_renovation_sponsored_museum
        124495,  # dramanode_npcinvite_date
        278850,  # situationdramanode_npcrelationshipautonomy_asktobe_bestfriend
        308901,  # dialogdramanode_jobloss_joboffer_business
        137934,  # dramanode_npcinvite_criticcareer_localhangout_museum
        199242,  # pickerdramanode_actorcareer_highbudgettv_police_gran
        301771,  # dialogdramanode_scenario_newintown_phase4_newacquaintancecaller_romancebar
        297386,  # situationdramanode_scenario_onboarding_newintown_phase4_acquaintedvisitor_2
        191047,  # situationdramanode_scarecrow_purple
        143041,  # npcinvite_cityinvites_festivals_fleamarket_buysomething
        283431,  # dialogdramanode_openablewindow_rmovie
        239231,  # pickerdramanode_freelancer_batuu_resistance_story_02
        195168,  # pickerdramanode_actorcareer_highbudgettv_western
        208047,  # pickerdramanode_freelancer_writer_fantasy_2
        309388,  # dialogdramanode_lifemilestone_caughtsimcheating_friend
        127382,  # dramanode_barnights_bearnight
        195052,  # dramanode_musicproductionstation_warningwithdinkybeats
        242085,  # pickerdramanode_freelancer_batuu_firstorder_story_mission_8
        254898,  # pickerdramanode_freelancer_paranormalinvestigator_2medium
        207659,  # pickerdramanode_freelancer_programmer_hack_server_system
        244018,  # pickerdramanode_freelancer_batuu_resistance_repeatable_02
        199185,  # pickerdramanode_actorcareer_highbudgettv_apocalypse_aistaffing
        260719,  # pickerdramanode_career_interiordecorator_room_addition_skill_room_handiness
        253296,  # pickerdramanode_freelancer_paranormalinvestigator_1easy
        239622,  # pickerdramanode_freelancer_batuu_firstorder_story_mission_1
        262501,  # pickerdramanode_villagerhelp_foodforage_short_groceryowner
        301256,  # dialogdramanode_scenario_newintown_phase1_intro
        207970,  # pickerdramanode_freelancer_programmer_virus_3
        263545,  # pickerdramanode_career_interiordecorator_room_renovations_kidsroom
        199802,  # dialogdramanode_actorcareer_aistaffing_post_gignotscheduled_5
        268972,  # dialogdramanode_villagerhelp_discoverytracker_npcvillager_pending
        126452,  # dramanode_npcinvite_clubfriends
        184762,  # lotterydramanode_holidaylottery
        198200,  # dramanode_actorcareer_performancefeedback_seriousbusiness_tvlow_low
        241934,  # pickerdramanode_freelancer_batuu_scoundrel_story_10
        239886,  # pickerdramanode_freelancer_batuu_firstorder_8
        199213,  # pickerdramanode_actorcareer_highbudgettv_police_wellsuited
        207532,  # pickerdramanode_freelancer_artist_forgery_3
        195441,  # dialogdramanode_quirk_publicnumber_angry
        212441,  # dialogdramanode_turtlehatching_reminder
        199235,  # pickerdramanode_actorcareer_film_superhero_gran
        233382,  # pickerdramanode_freelancer_maker_rug_02
        143048,  # npcinvite_cityinvites_festivals_food_harvest
        302208,  # dialogdramanode_scenario_stuckintheirshadow_4aastronautoffer
        222022,  # pickerdramanode_freelancer_fashion_photographer_style_2
        282997,  # dialogdramanode_openablewindow_collegeparty
        288769,  # dramanode_highschool_active_nobackgroundevent
        255190,  # dialogdramanode_career_interiordecorator_followup_clientcall_returning_positive
        226815,  # dialogdramanode_loans_secondcall
        227820,  # venueeventdramanode_university_studentcommons_arts_debatepractice_wed
        216021,  # pickerdramanode_freelancer_fashion_photographer_everyday_wear
        279014,  # venueeventdramanode_thriftstore_openmic_comedy
        294429,  # dialogdramanode_werewolfpackbenefits_packbtreats
        211473,  # pickerdramanode_oddjob_packing
        267007,  # pickerdramanode_career_interiordecorator_room_renovations_walkin_closet
        229458,  # dialogdramanode_collegeorganizations_reminder
        207993,  # pickerdramanode_freelancer_programmer_hack_server_system_2
        125784,  # dialogdramanode_goingoutsocials_offlot_trashanothersim
        199180,  # pickerdramanode_actorcareer_film_pirate_aistaffing
        231248,  # pickerdramanode_freelancer_batuu_firstorder_1
        143034,  # npcinvite_cityinvites_venueinvites_bar
        199795,  # dialogdramanode_actorcareer_aistaffing_post_gigscheduled_6
        227616,  # collegeorganization_dramanodes_events_secretsociety_ritual_fri
        309232,  # stayoverdramanode_friend
        190853,  # dramanode_npcinvite_date_holiday
        198193,  # dramanode_actorcareer_performancefeedback_hangten_tvlow_high
        211471,  # pickerdramanode_oddjob_hiking
        339186,  # dialogdramanode_scenario_inheritance_grandma_1c_donate
        233683,  # situationdramanode_communitycloseness_sparerecyclings
        199202,  # pickerdramanode_actorcareer_commercial_western_wellsuited
        291166,  # dialogdramanode_werewolf_text
        205593,  # islandevents_small_dramanode_beachbonfire
        339176,  # dialogdramanode_scenario_inheritance_grandma_1a
        125708,  # dialogdramanode_congratsonbaby
        195446,  # dialogdramanode_quirk_publicnumber_stressed
        209016,  # pickerdramanode_oddjob_treasure
        234029,  # pickerdramanode_freelancer_maker_jarcandles_03
        280278,  # dramanode_npcinvite_movein
        268601,  # dialogdramanode_villagerhelp_discoverytracker_npcvillager_day8
        261820,  # pickerdramanode_career_interiordecorator_level_renovation_commercial_club
        234039,  # pickerdramanode_freelancer_maker_kombucha_02
        154433,  # dialogdramanode_introtovampire_call0
        258359,  # dialogdramanode_career_interiordecorator_followup_tv_negative_preshow_thu
        143055,  # npcinvite_cityinvites_festivals_logic_motiongaming
        283433,  # dialogdramanode_openablewindow_loitering
        308905,  # dialogdramanode_jobloss_joboffer_painter
        231583,  # dialogdramanode_communitycloseness_borrowsimoleons_initial
        276073,  # playerplannedweddingdramanode
        182316,  # test_holidaydramanode
        234054,  # pickerdramanode_freelancer_maker_craftedcandle_01
        308931,  # dialogdramanode_jobloss_joboffer_criminal
        273857,  # dialogdramanode_askifnewjob
        140083,  # festivaldramanode_blossomfestival
        231585,  # dialogdramanode_communitycloseness_wrongnumber
        280463,  # dramanode_npcinvite_story_progression_childrenstories_adoptedbaby
        243867,  # pickerdramanode_freelancer_batuu_resistance_repeatable_8
        196249,  # pickerdramanode_actorcareer_commercial_housenice
        227615,  # collegeorganization_dramanodes_events_secretsociety_ritual_wed
        207794,  # pickerdramanode_freelancer_writer_motivational_book
        294426,  # dialogdramanode_werewolfpackbenefits_packatreats
        194477,  # runaffordancedramanode_actorcareer_auditions_tvlow_houselow
        244137,  # pickerdramanode_freelancer_batuu_scoundrel_9
        258069,  # dialogdramanode_career_interiordecorator_followup_tv_positive_postshow
        195210,  # dramanode_reputation_good_throwcharitybenefitparty
        316136,  # runaffordancedramanode_phone_chattycall
        125791,  # dialogdramanode_goingoutsocials_offlot_matchmake_inrelationship
        199173,  # pickerdramanode_actorcareer_commercial_housenice_aistaffing
        211462,  # pickerdramanode_oddjob_treasurecleaning
        198198,  # dramanode_actorcareer_performancefeedback_hangten_movie_med
        297845,  # situationdramanode_scenario_onboarding_stuckintheirshadow_rivalvisit
        199227,  # pickerdramanode_actorcareer_commercial_housenice_gran
        152316,  # dramanode_vampirecreation_invitetotransform_nohome
        195694,  # dramanode_reputation_bad_career_criminal
        199790,  # dialogdramanode_actorcareer_aistaffing_post_gigscheduled_1
        127797,  # clubgatheringdramanode_default
        209015,  # pickerdramanode_oddjob_naturepictures
        207546,  # pickerdramanode_freelancer_artist_splash_art_2
        198188,  # dramanode_actorcareer_performancefeedback_estellegable_movie_low
        208760,  # pickerdramanode_freelancer_programmer_spreadsheet_setup_2
        296532,  # dialogdramanode_scenario_stuckintheirshadow_2optionalpto
        339183,  # dialogdramanode_scenario_inheritance_grandma_3a_ghostinvited
        219738,  # pickerdramanode_freelancer_fashion_photographer_poses_2
        180376,  # npcinvite_cityinvites_festivals_blossom_kiss_teen
        195153,  # pickerdramanode_actorcareer_lowbudgettv_western
        199249,  # pickerdramanode_actorcareer_lowbudgettv_pirate_gran
        234250,  # runaffordancedramanode_freelancer_offergig_maker
        234046,  # pickerdramanode_freelancer_maker_carvedcandle_01
        311526,  # stayoverdramanode_couchsurf
        273994,  # dialogdramanode_neighborrelphonecall_initial_friendly
        198210,  # dramanode_actorcareer_performancefeedback_wearereallyhuman_tvlow_med
        278855,  # situationdramanode_npcrelationshipautonomy_propose
        258346,  # dialogdramanode_career_interiordecorator_followup_tv_negative_postshow
        164962,  # dialogdramanode_fixbadrelationship
        195637,  # dramanode_reputation_good_career_gardener
        208052,  # pickerdramanode_freelancer_writer_mystery_2
        210100,  # runaffordancedramanode_freelancer_offergig_programmer
        141200,  # festivaldramanode_logicfair
        262484,  # pickerdramanode_villagerhelp_livestockshort_groceryowner
        129417,  # clubinviterequestdramanode_requestinvite_inviteonly
        232843,  # pickerdramanode_freelancer_maker_rug_01
        260730,  # pickerdramanode_career_interiordecorator_room_addition_skill_room_videogaming
        309387,  # dialogdramanode_lifemilestone_caughtcheatingbysim_exso
        258886,  # pickerdramanode_career_interiordecorator_level_addition
        194466,  # runaffordancedramanode_actorcareer_auditions_movie_city
        214795,  # pickerdramanode_freelancer_fashion_photographer_outdoor_wear
        207991,  # pickerdramanode_freelancer_programmer_hack_listerv_3
        244025,  # pickerdramanode_freelancer_batuu_scoundrel_10
        199194,  # pickerdramanode_actorcareer_lowbudgettv_pirate_aistaffing
        197146,  # loungevenueevents_meetacelebrity_monday
        207791,  # pickerdramanode_freelancer_writer_marketing_copy
        221715,  # situationdramanode_roommatenpc_gethype
        199353,  # dialogdramanode_actorcareer_gran_auditionsuccess
        207981,  # pickerdramanode_freelancer_programmer_computer_game_2
        297475,  # dialogdramanode_bestiephonecall_intro
        207537,  # pickerdramanode_freelancer_artist_logo_design_2
        125981,  # dialogdramanode_congratsonsignificantother
        299973,  # dialogdramanode_scenario_newintown_phase4_intro
        267034,  # pickerdramanode_career_interiordecorator_room_addition_walkin_closet
        188849,  # situationdramanode_scarecrow
        198181,  # dramanode_actorcareer_performancefeedback_wearereallyhuman_commercial_high
        195295,  # dialogdramanode_quirk_publicnumber_happy
        127430,  # dramanode_npcinvite_godancing_bluffs
        195604,  # dramanode_reputation_good_career_astronaut
        127220,  # dramanode_npcinvite_energizedtext
        282944,  # dialogdramanode_hsprom_lockerinvite_success
        246533,  # festivaldramanodes_youthfestival
        195148,  # pickerdramanode_actorcareer_commercial_kids
        199244,  # pickerdramanode_actorcareer_highbudgettv_western_gran
        263188,  # pickerdramanode_villagerhelp_livestockgardenlong_groceryowner
        231576,  # dialogdramanode_communitycloseness_commitmentissues
        143043,  # npcinvite_cityinvites_festivals_fleamarket_watchperformer
        234416,  # situationdramanode_communitycloseness_complaint_ecomaster
        283429,  # dialogdramanode_openablewindow_sleepover
        308156,  # dialogdramanode_jobloss_layoff_freepizza
        195170,  # pickerdramanode_actorcareer_film_superhero
        196093,  # dramanode_reputation_bad_illgottengains
        208033,  # pickerdramanode_freelancer_writer_marketing_copy_2
        195054,  # dramanode_musicproductionstation_warningwithnewtastemakers
        267677,  # pickerdramanode_career_interiordecorator_room_addition_commercial_bathrooms
        237711,  # pickerdramanode_freelancer_batuu_resistance_story_01
        199187,  # pickerdramanode_actorcareer_highbudgettv_police_aistaffing
        207661,  # pickerdramanode_freelancer_programmer_hack_nssa
        260713,  # pickerdramanode_career_interiordecorator_room_addition_skill_room_programming
        226465,  # collegeorganizationevents_barnight_prank
        262503,  # pickerdramanode_villagerhelp_foodforage_short_pubowner
        274053,  # dialogdramanode_neighborrelphonecall_followup_friendly_furtherfriendship
        227277,  # dialogdramanode_e-sports_opportunity
        207972,  # pickerdramanode_freelancer_programmer_website_2
        187462,  # dialogdramanode_sendforgedbreakupletter_divorced
        143029,  # npcinvite_cityinvites_festivals_blossom_kiss
        298530,  # dialogdramanode_scenario_parentingpredicament_principal_phase3
        267027,  # pickerdramanode_career_interiordecorator_room_renovations_sponsored_bar
        198202,  # dramanode_actorcareer_performancefeedback_seriousbusiness_tvlow_high
        216074,  # pickerdramanode_freelancer_fashion_photographer_lights
        244215,  # pickerdramanode_freelancer_batuu_firstorder_repeatable_03
        207445,  # pickerdramanode_freelancer_artist_public_artist
        219720,  # pickerdramanode_freelancer_fashion_photographer_formal_wear_2
        241932,  # pickerdramanode_freelancer_batuu_scoundrel_story_08
        199215,  # pickerdramanode_actorcareer_highbudgettv_western_wellsuited
        224020,  # dialogdramanode_university_finalexam_caughtcheating
        207534,  # pickerdramanode_freelancer_artist_icons_2
        195443,  # dialogdramanode_quirk_publicnumber_sad
        234024,  # pickerdramanode_freelancer_maker_jarcandles_01
        296657,  # dialogdramanode_scenario_stuckintheirshadow_4arivalnewjob
        202887,  # dramanode_reputation_good_career_socialmedia
        299014,  # dialogdramanode_scenario_stuckintheirshadow_3rival_fired_ifmissed
        268604,  # dialogdramanode_villagerhelp_discoverytracker_offerhelp_day7
        137943,  # dramanode_npcinvite_criticcareer_localhangout_bar
        199237,  # pickerdramanode_actorcareer_film_western_gran
        229272,  # dialogdramanode_university_enrollmentinfo
        263187,  # pickerdramanode_villagerhelp_livestockgardenlong_agnescrumplebottom
        310173,  # playerplannedstayoverdramanode
        234034,  # pickerdramanode_freelancer_maker_sofa_02
        258360,  # dialogdramanode_career_interiordecorator_followup_tv_negative_preshow_tue
        143050,  # npcinvite_cityinvites_festivals_lamp_buyshirt
        262490,  # pickerdramanode_villagerhelp_gardenshort_agnescrumplebottom
        231578,  # dialogdramanode_communitycloseness_feelingblue
        226813,  # dialogdramanode_loans_firstcall
        244347,  # pickerdramanode_freelancer_batuu_resistance_repeatable_13
        259970,  # festivalcontestdramanode_villagefair_llamawool
        308849,  # dialogdramanode_jobloss_joboffer_athletic
        297042,  # dialogdramanode_scenario_newintown_phase2_intro
        309381,  # dialogdramanode_lifemilestone_fellinlove_exso
        268608,  # dialogdramanode_villagerhelp_discoverytracker_npcvillager_day2_tns
        194480,  # runaffordancedramanode_actorcareer_auditions_tvlow_western
        201191,  # dramanode_reputation_bad_childtakenaway
        216023,  # pickerdramanode_freelancer_fashion_photographer_swim_wear
        195217,  # dramanode_reputation_bad_disliked
        279012,  # venueeventdramanode_thriftstore_fashion_monday
        267247,  # pickerdramanode_career_interiordecorator_level_renovation_commercial_cafe
        128361,  # dialogdramanode_goingoutsocials_offlot_breakupsims_divorce
        187763,  # dialogdramanode_sendforgedbreakupletter_foundout
        269980,  # dialogdramanode_musicfestival2021_npc_phone_call
        275579,  # dialogdramanode_goingoutsocials_offlot_talkupsim_conflictingtraits
        244407,  # pickerdramanode_freelancer_batuu_scoundrel_6
        125786,  # dialogdramanode_goingoutsocials_offlot_talkupsim_success
        185409,  # dialogdramanode_mailbox_sendgift
        143036,  # npcinvite_cityinvites_venueinvites_karaoke
        199797,  # dialogdramanode_actorcareer_aistaffing_post_gignotscheduled_1
        199182,  # pickerdramanode_actorcareer_film_victorian_aistaffing
        211465,  # pickerdramanode_oddjob_wingman
        198195,  # dramanode_actorcareer_performancefeedback_hangten_tvhigh_med
        225717,  # situationdramanode_universitygraduation_arts
        281000,  # venueeventdramanode_thriftstore_fashion_friday
        233681,  # situationdramanode_communitycloseness_complaint_despised
        338187,  # dramanode_npcinvite_story_progression_childrenstories_adoptedhorse
        241927,  # pickerdramanode_freelancer_batuu_scoundrel_story_03
        199204,  # pickerdramanode_actorcareer_film_dancingintherain_wellsuited
        199787,  # dialogdramanode_actorcareer_aistaffing_post_generic1
        131898,  # dialogdramanode_experimentalfoodphoto
        224237,  # dialogdramanode_university_caughtcheating_termpaper
        209018,  # pickerdramanode_oddjob_beachmenace
        279973,  # dialogdramanode_hsteam_switch_cheerteam
        198185,  # dramanode_actorcareer_performancefeedback_estellegable_tvhigh_low
        261265,  # pickerdramanode_villagerhelp_socialshort_mayor
        339178,  # dialogdramanode_scenario_inheritance_grandma_2a
        268603,  # dialogdramanode_villagerhelp_discoverytracker_offerhelp_day3
        280605,  # dialogdramanode_story_progression_childrenstories_impregnant
        261822,  # pickerdramanode_career_interiordecorator_level_renovation_commercial_library
        127297,  # dramanode_npcinvite_angrytext
        195608,  # dramanode_reputation_good_career_culinary
        260779,  # pickerdramanode_career_interiordecorator_room_addition_skill_room_gardening
        231581,  # dialogdramanode_communitycloseness_importantquestions
        235004,  # situationdramanode_communitycloseness_complaint_followup
        269931,  # dialogdramanode_musicfestival2021_ticketgift
        234052,  # pickerdramanode_freelancer_maker_kidbed_03
        140085,  # festivaldramanode_fleamarket
        195222,  # dramanode_reputation_bad_neighborhoodhivemind
        262233,  # pickerdramanode_villagerhelp_mayor
        296149,  # situationdramanode_scenario_onboarding_newintown_phase4_acquaintedvisitor_1
        207796,  # pickerdramanode_freelancer_writer_fantasy
        183095,  # dramanode_premadeholiday_surprise_nightonthetown
        128981,  # dramanode_npc_invite_sadtext
        194479,  # runaffordancedramanode_actorcareer_auditions_tvlow_housenice
        198162,  # dramanode_actorcareer_performancefeedback_hangten_commercial_low
        194066,  # dialogdramanode_corporatepartnership_addtrend1
        216146,  # pickerdramanode_freelancer_fashion_photographer_outdoor_wear_2
        263106,  # pickerdramanode_career_interiordecorator_room_renovations_kitchen
        207986,  # pickerdramanode_freelancer_programmer_encryption_4
        269971,  # dialogdramanode_musicfestival2021_closebusinesses
        199175,  # pickerdramanode_actorcareer_commercial_pirate_aistaffing
        264789,  # pickerdramanode_career_interiordecorator_level_addition_top_floor_family_room
        128959,  # dramanode_phone_npcinvite
        211456,  # pickerdramanode_oddjob_bartend
        298901,  # dialogdramanode_werewolfrepairman
        207976,  # pickerdramanode_freelancer_programmer_mobile_app_3
        244384,  # pickerdramanode_freelancer_batuu_scoundrel_8
        274690,  # dramanode_npcinvite_discussexpandingthefamily_hadbaby_targetsimpartner
        259801,  # pickerdramanode_career_interiordecorator_level_renovation_commercial_bar
        199229,  # pickerdramanode_actorcareer_commercial_pirate_gran
        241950,  # pickerdramanode_freelancer_batuu_resistance_story_08
        297847,  # situationdramanode_scenario_onboarding_stuckintheirshadow_friendvisit
        209009,  # pickerdramanode_oddjob_beachcomb_trash
        269621,  # festivaldramanode_musicfestival
        198190,  # dramanode_actorcareer_performancefeedback_estellegable_movie_high
        267377,  # pickerdramanode_career_interiordecorator_room_renovations_high
        207449,  # pickerdramanode_freelancer_artist_splash_art
        195155,  # pickerdramanode_actorcareer_lowbudgettv_pirate
        301778,  # situationdramanode_scenario_onboarding_stuckintheirshadow_lastinvite
        296524,  # dialogdramanode_scenario_stuckintheirshadow_4arivalpurchases
        234044,  # pickerdramanode_freelancer_maker_floorlight_03
        196010,  # dramanode_npcinvite_date_reputation_bad
        260768,  # pickerdramanode_career_interiordecorator_room_addition_skill_room_mixology
        198212,  # dramanode_actorcareer_performancefeedback_wearereallyhuman_tvhigh_low
        278853,  # situationdramanode_npcrelationshipautonomy_asktoprom_asfriends
        308902,  # dialogdramanode_jobloss_joboffer_culinary
        274409,  # dialogdramanode_goingoutsocials_offlot_matchmake_conflictingtraits
        193591,  # dialogdramanode_corporatepartnership
        198712,  # runaffordancedramanode_actorcareer_agency_seriousbusiness_offergig_tutorial
        154176,  # situationdramanode_vampire_homeinvasion
        283688,  # dramanode_highschool_active_debug_exam
        208044,  # pickerdramanode_freelancer_writer_non_fiction_3
        205653,  # islandevents_large_dramanode_turtlehatching
        309385,  # dialogdramanode_lifemilestone_caughtcheatingbysim_friend
        294413,  # dialogdramanode_werewolf_joinpackrequest
        194468,  # runaffordancedramanode_actorcareer_auditions_movie_pirate
        214837,  # runaffordancedramanode_freelancer_offergig_fashion_photographer
        207656,  # pickerdramanode_freelancer_programmer_computer_game
        244702,  # pickerdramanode_freelancer_batuu_firstorder_repeatable_05
        187759,  # dialogdramanode_sendforgedbreakupletter_hadfight
        207983,  # pickerdramanode_freelancer_programmer_computer_game_5
        199218,  # pickerdramanode_actorcareer_lowbudgettv_housenice_wellsuited
        227626,  # collegeorganizations_dramanodes_events_paintininthepark_monday
        198183,  # dramanode_actorcareer_performancefeedback_estellegable_tvlow_med
        241931,  # pickerdramanode_freelancer_batuu_scoundrel_story_07
        199208,  # pickerdramanode_actorcareer_film_victorian_wellsuited
        207529,  # pickerdramanode_freelancer_artist_environment_concept_3
        212665,  # dialogdramanode_caughtendangeredfish_fine
        195606,  # dramanode_reputation_good_career_athletic
        299009,  # dialogdramanode_scenario_stuckintheirshadow_1rivalcall_intro_ifmissed
        208690,  # islandevents_large_dramanode_fishingcompetition
        268599,  # dialogdramanode_villagerhelp_discoverytracker_npcvillager_day2
        202593,  # dialogdramanode_quirk_publicnumber_stressed_t2t
        199246,  # pickerdramanode_actorcareer_lowbudgettv_houselow_gran
        195172,  # pickerdramanode_actorcareer_film_pirate
        259973,  # festivalcontestdramanode_villagefair_giantcroppie
        208035,  # pickerdramanode_freelancer_writer_clickbait_article_2
        207795,  # pickerdramanode_freelancer_writer_non_fiction
        183097,  # dramanode_premadeholiday_surprise_discountday
        127386,  # dramanode_barnights_singlesnight
        267679,  # pickerdramanode_career_interiordecorator_room_addition_commercial_arcade
        239926,  # pickerdramanode_freelancer_batuu_firstorder_9
        199189,  # pickerdramanode_actorcareer_highbudgettv_western_aistaffing
        262229,  # pickerdramanode_villagerhelp_agathacrumplebottom_1
        274055,  # dialogdramanode_neighborrelphonecall_followup_friendly_nofurtherfriendship
        149698,  # npcinvite_cityinvites_festivals_all_buyashirt
        143031,  # npcinvite_cityinvites_festivals_logic_observatory
        199179,  # pickerdramanode_actorcareer_film_medieval_aistaffing
        297065,  # dramanode_npcinvite_date_newintown_phase4
        211468,  # pickerdramanode_oddjob_furnitureinstalling
        198204,  # dramanode_actorcareer_performancefeedback_seriousbusiness_tvhigh_med
        155679,  # npcinvite_cityinvites_festivals_buyashirt_food
        207447,  # pickerdramanode_freelancer_artist_environment_concept
        199201,  # pickerdramanode_actorcareer_commercial_pirate_wellsuited
        227677,  # collegeorganizationevents_studygroup_library_wednesday
        195445,  # dialogdramanode_quirk_publicnumber_flirty
        281853,  # highschoolfestival_sciencefair_chess
        219728,  # pickerdramanode_freelancer_fashion_photographer_swim_wear_2
        187999,  # customholidaydramanode
        199239,  # pickerdramanode_actorcareer_highbudgettv_apocalypse_gran
        227928,  # collegeorganizations_events_schoolspirit_prank_gamedayparty_saturday
        143052,  # npcinvite_cityinvites_festivals_lamp_eatfood
        198216,  # dramanode_actorcareer_performancefeedback_wearereallyhuman_movie_med
        236677,  # dialogdramanode_entrepreneur_high
        308906,  # dialogdramanode_jobloss_joboffer_secretagent
        199107,  # situationdramanode_roommatevisit
        198710,  # runaffordancedramanode_actorcareer_agency_estellegable_offergig_tutorial
        235084,  # situationdramanode_civicinspector
        260890,  # pickerdramanode_villagerhelp_agnescrumplebottom_1
        226462,  # collegeorganizationevents_barnight_artsociety
        228041,  # dialogdramanode_university_sportsarena_gamedayreminder_esports_arts
        234051,  # pickerdramanode_freelancer_maker_kidbed_02
        231586,  # dialogdramanode_communitycloseness_dreamofyou
        263201,  # pickerdramanode_villagerhelp_socialmedium_pubowner
        195219,  # dramanode_reputation_bad_pettakenaway
        309403,  # dialogdramanode_lifemilestone_caughtsimcheating_family
        207654,  # pickerdramanode_freelancer_programmer_website
        196074,  # dramanode_reputation_bad_addnewfriend
        245159,  # pickerdramanode_freelancer_batuu_resistance_repeatable_07
        194472,  # runaffordancedramanode_actorcareer_auditions_tvhigh_victorian
        221593,  # venueeventdramanode_university_studentcommons_arts_poetry
        195209,  # dramanode_reputation_good_donate
        232871,  # dialogdramanode_communitycloseness_borrowsimoleons_followup
        134428,  # dramanode_npcinvite_restaurant_condolences
        125788,  # dialogdramanode_goingoutsocials_offlot_talkupsim_fail
        143038,  # npcinvite_cityinvites_festivals_blossom_meetpeople
        199799,  # dialogdramanode_actorcareer_aistaffing_post_gignotscheduled_3
        261125,  # pickerdramanode_career_interiordecorator_room_addition_nursery
        222193,  # venueeventdramanode_university_studentcommons_arts_examcram
        268121,  # pickerdramanode_villagerhelp_socialmedium_agathacrumplebottom
        211467,  # pickerdramanode_oddjob_divinginstructor
        198197,  # dramanode_actorcareer_performancefeedback_hangten_movie_low
        237859,  # dialogdramanode_communitycloseness_civicpolicycall
        283489,  # npcinvitesituationdramanode_hsprom_postpromdramanode
        274255,  # dialogdramanode_discussexpandingthefamily_impregnant_targetsimpartner
        261505,  # pickerdramanode_villagerhelp_socialshort_pubowner
        199206,  # pickerdramanode_actorcareer_film_pirate_wellsuited
        199789,  # dialogdramanode_actorcareer_aistaffing_post_generic3
        309230,  # stayoverdramanode_couchsurf_kyle
        124497,  # dramanode_npcinvite_playdate
        339180,  # dialogdramanode_scenario_inheritance_grandma_2c_healedsentiment
        209012,  # pickerdramanode_oddjob_kaluapork
        198187,  # dramanode_actorcareer_performancefeedback_estellegable_tvhigh_high
        195164,  # pickerdramanode_actorcareer_highbudgettv_apocalypse
        234043,  # pickerdramanode_freelancer_maker_floorlight_02
        154437,  # dialogdramanode_introtovampire_call4
        198209,  # dramanode_actorcareer_performancefeedback_wearereallyhuman_tvlow_low
        260554,  # pickerdramanode_career_interiordecorator_room_addition_skill_room_photography
        308909,  # dialogdramanode_jobloss_joboffer_techguru
        206612,  # pickerdramanode_freelancer_artist_sketch_artist
        269314,  # dialogdramanode_villagerhelp_discoverytracker_npcvillager_day8_call
        195632,  # dramanode_reputation_good_career_secretagent
        300774,  # dialogdramanode_scenario_newintown_phase4_nextphasephonecall
        208049,  # pickerdramanode_freelancer_writer_science_fiction_2
        234058,  # pickerdramanode_freelancer_maker_finewalldecor_01
        273861,  # dialogdramanode_gotpromotion
        142870,  # dramanode_cityinvites_rabbithole_concert
        207966,  # pickerdramanode_freelancer_programmer_mod_game_2
        300126,  # dialogdramanode_childhoodfriends_bff
        125996,  # dialogdramanode_newfriend
        207798,  # pickerdramanode_freelancer_writer_mystery
        183093,  # dramanode_premadeholiday_surprise_prankday
        194465,  # runaffordancedramanode_actorcareer_auditions_movie_western
        194068,  # dialogdramanode_corporatepartnership_addtrend3
        198164,  # dramanode_actorcareer_performancefeedback_seriousbusiness_commercial_low
        195214,  # dramanode_reputation_bad_fighting
        258065,  # dialogdramanode_career_interiordecorator_followup_tv_positive_preshow_thu
        266257,  # pickerdramanode_career_interiordecorator_level_addition_top_floor_photography
        267659,  # pickerdramanode_career_interiordecorator_level_addition_shelevel
        216156,  # pickerdramanode_freelancer_fashion_photographer_sleep_wear_2
        199193,  # pickerdramanode_actorcareer_lowbudgettv_kids_aistaffing
        197145,  # loungevenueevents_awardceremony
        265013,  # festivalcontestsubdramanode_villagefair_pie
        280737,  # prominvitedramanode_hsprom
        297063,  # dramanode_scenario_npcinvite_newintown_phase4_lounge
        198599,  # npcinvite_loungeevent_openmic
        211458,  # pickerdramanode_oddjob_portrait
        258063,  # dialogdramanode_career_interiordecorator_followup_tv_positive_preshow_tue
        241948,  # pickerdramanode_freelancer_batuu_resistance_story_06
        274845,  # dialogdramanode_asksimtopursuedreamjob_nocareerchange
        209011,  # pickerdramanode_oddjob_coconut
        207451,  # pickerdramanode_freelancer_artist_logo_design
        195157,  # pickerdramanode_actorcareer_lowbudgettv_kids
        195736,  # dramanode_reputation_good_addnewfriend
        125699,  # dialogdramanode_congratsonpromotion
        239706,  # pickerdramanode_freelancer_batuu_scoundrel_story_02
        226559,  # dialogdramanode_university_soccerteam_prosports
        198214,  # dramanode_actorcareer_performancefeedback_wearereallyhuman_tvhigh_high
        278851,  # situationdramanode_npcrelationshipautonomy_asktobe_boyfriendgirlfriend
        263015,  # pickerdramanode_villagerhelp_narrative_agathacrumplebottom_2
        199243,  # pickerdramanode_actorcareer_highbudgettv_victorian_gran
        143040,  # npcinvite_cityinvites_festivals_blossom_throwpetals
        191046,  # situationdramanode_scarecrow_red
        258332,  # dramanode_npcinvite_career_interiordecorator_followup_clientcall
        297048,  # dialogdramanode_scenario_newintown_phas3bintro
        125814,  # clubinvitedramanode_joinclubstranger
        194470,  # runaffordancedramanode_actorcareer_auditions_movie_victorian
        127383,  # dramanode_barnights_aliensnight
        195053,  # dramanode_musicproductionstation_warningwithmaxismusicmachine
        223264,  # situationdramanode_roommatenpc_lockedout
        254899,  # pickerdramanode_freelancer_paranormalinvestigator_3hard
        270127,  # dialogdramanode_musicfestival2021_npc_phone_call_return
        207525,  # pickerdramanode_freelancer_artist_character_concept_2
        207658,  # pickerdramanode_freelancer_programmer_hack_listerv
        199198,  # pickerdramanode_actorcareer_commercial_hospital_wellsuited
        197150,  # loungevenueevents_meetacelebrity_wednesday
        243713,  # pickerdramanode_freelancer_batuu_neutral_repeatable_mission_02
        187961,  # dialogdramanode_mailbox_sendgift_toddler
        207969,  # pickerdramanode_freelancer_programmer_virus_2
        199220,  # pickerdramanode_actorcareer_lowbudgettv_pirate_wellsuited
        201268,  # npcinvite_dramanode_situation_reputation_lampoonparty
        207541,  # pickerdramanode_freelancer_artist_portrait_3
        283713,  # dramanode_highschool_active_firedrill
        198201,  # dramanode_actorcareer_performancefeedback_seriousbusiness_tvlow_med
        223210,  # collegeorganizations_dramanodes_events_roboticsexhibition
        204566,  # islandevents_small_dramanode_townpotluck
        125853,  # dramanode_npcinvite_date_goingoutsocials
        207531,  # pickerdramanode_freelancer_artist_forgery_2
        234021,  # pickerdramanode_freelancer_maker_tofizz_02
        208992,  # situationdramanode_islanderculture_needsomethingfixed
        182428,  # playerplanneddramanode
        199232,  # pickerdramanode_actorcareer_film_dancingintherain_gran
        222226,  # venueeventdramanode_university_studentcommons_science_examcram
        143047,  # npcinvite_cityinvites_festivals_food_eatburrito
        205744,  # islandevents_small_dramanode_familyfunday
        238028,  # dialogdramanode_batuu_calltoaction
        231575,  # dialogdramanode_communitycloseness_inheritance
        195174,  # pickerdramanode_actorcareer_film_dancingintherain
        267252,  # pickerdramanode_career_interiordecorator_level_addition_famous_low_fame
        209046,  # collegeorganizationevents_studygroup_library
        280465,  # dramanode_npcinvite_story_progression_childrenstories_adoptedchild
        268796,  # dramanode_donothing_foxsupression
        208037,  # pickerdramanode_freelancer_writer_clickbait_article_4
        127384,  # dramanode_barnights_ghostsnight
        216020,  # pickerdramanode_freelancer_fashion_photographer_athletic_wear
        263204,  # pickerdramanode_villagerhelp_wildanimalfoodlong_crittertender
        294839,  # dialogdramanode_scenario_stuckintheirshadow_1rivalcall_intro
        199191,  # pickerdramanode_actorcareer_lowbudgettv_houselow_aistaffing
        262231,  # pickerdramanode_villagerhelp_grocerydelivery
        211472,  # pickerdramanode_oddjob_judge
        267004,  # pickerdramanode_career_interiordecorator_level_addition_top_floor_tile_restriction_office_bath
        148689,  # npcinvite_cityinvites_festivals_food_blowbubbles
        198168,  # dramanode_actorcareer_performancefeedback_wearereallyhuman_commercial_med
        124845,  # dialogdramanode_phone_invitenpcover
        199181,  # pickerdramanode_actorcareer_film_superhero_aistaffing
        143033,  # npcinvite_cityinvites_festivals_logic_program
        199792,  # dialogdramanode_actorcareer_aistaffing_post_gigscheduled_3
        223084,  # collegeorganizations_events_schoolspirit_prank_creativitycelebration
        309235,  # stayoverdramanode_householdloss
        339185,  # dialogdramanode_scenario_inheritance_grandma_3b_ghostinvited
        211470,  # pickerdramanode_oddjob_gaming
        198206,  # dramanode_actorcareer_performancefeedback_seriousbusiness_movie_low
        233682,  # situationdramanode_communitycloseness_handyneighbor
        227675,  # collegeorganizationevents_studygroup_library_tuesday
        296661,  # dialogdramanode_scenario_stuckintheirshadow_4bindies
        268600,  # dialogdramanode_villagerhelp_discoverytracker_npcvillager_day4
        208788,  # collegeorganizations_dramanodes_events_schoolspirit_party_schoolspiritday
        261821,  # pickerdramanode_career_interiordecorator_level_renovation_commercial_gym
        320401,  # dialogdramanode_lifemilestone_intro
        226976,  # venueeventdramanode_university_studentcommons_science_robotbuilding_thursday
        234038,  # pickerdramanode_freelancer_maker_kombucha_01
        154434,  # dialogdramanode_introtovampire_call1
        258356,  # dialogdramanode_career_interiordecorator_followup_tv_negative_preshow_mon
        143054,  # npcinvite_cityinvites_festivals_logic_buildrocket
        283434,  # dialogdramanode_openablewindow_hangout
        194462,  # runaffordancedramanode_actorcareer_auditions_commercial_hospital
        231582,  # dialogdramanode_communitycloseness_startedmybusiness
    )


log = BBLogRegistry().register_log(ModIdentity(), 'bbs_drama_node_disabler')
log.enable()


@BBInjectionUtils.inject(ModIdentity(), BaseDramaNode, BaseDramaNode._test.__name__)
def _bbs_disable_drama_nodes(original, self, *_, **__) -> TestResult:
    drama_node_id = getattr(self, 'guid64')
    if drama_node_id in BBDramaNodeDisabler.DISABLED_DRAMA_NODE_IDS:
        log.debug('Preventing BaseDramaNode Drama Node from starting.', drama_node=self, drama_node_id=drama_node_id)
        return False
    return original(self, *_, **__)
