from typing import Tuple, List

from bbsurvival.bb_lib.utils.bb_instance_utils import BBInstanceUtils
from bbsurvival.mod_identity import ModIdentity
from bluuberrylibrary.logs.bb_log_registry import BBLogRegistry
from bluuberrylibrary.utils.debug.bb_injection_utils import BBInjectionUtils
from drama_scheduler.drama_node import BaseDramaNode
from event_testing.results import TestResult
from sims4.commands import Command, CommandType
from sims4.resources import Types

log = BBLogRegistry().register_log(ModIdentity(), 'bbl_drama_nodes')
log.enable()


@Command(
    'bbs.print_drama_nodes',
    command_type=CommandType.Live
)
def _bbs_command_print_drama_nodes(_connection: int = None):
    from sims4.commands import CheatOutput
    output = CheatOutput(_connection)
    try:
        output(f'Printing Drama Nodes.')
        instances: List[Tuple[int, str]] = list()
        for (resource_key, instance) in BBInstanceUtils.get_all_instances(Types.DRAMA_NODE, return_type=BaseDramaNode):
            instance: BaseDramaNode = instance
            instance_tuning_name = instance.__name__.lower()
            guid64 = getattr(instance, 'guid64', None)
            instances.append((guid64, instance_tuning_name))

        sorted_instances = sorted(instances, key=lambda x: x[1])
        for (_guid64, _instance_tuning_name) in sorted_instances:
            log.debug(f'{_guid64},  # {_instance_tuning_name}')
        output('Done')
    except Exception as ex:
        output('Error occurred.')
        log.error('Problem occurred', exception=ex)


# @BBInjectionUtils.inject(ModIdentity(), Situation, Situation.start_situation.__name__)
def _bbs_disable_walkby_ambient(original, self, *_, **__):
    pass


class BBDramaNodeDisabler:
    DISABLED_DRAMA_NODE_IDS = (
        127797,  # clubgatheringdramanode_default
        125787,  # clubinvitedramanode_joinclubfriend
        125814,  # clubinvitedramanode_joinclubstranger
        129417,  # clubinviterequestdramanode_requestinvite_inviteonly
        129418,  # clubinviterequestdramanode_requestinvite_notinviteonly
        223009,  # collegeorganization_dramanodes_events_secretsociety_ritual
        227616,  # collegeorganization_dramanodes_events_secretsociety_ritual_fri
        227615,  # collegeorganization_dramanodes_events_secretsociety_ritual_wed
        226462,  # collegeorganizationevents_barnight_artsociety
        226463,  # collegeorganizationevents_barnight_debatesociety
        226461,  # collegeorganizationevents_barnight_honorsociety
        227733,  # collegeorganizationevents_barnight_party_sunday
        228547,  # collegeorganizationevents_barnight_party_wednesday
        226465,  # collegeorganizationevents_barnight_prank
        226464,  # collegeorganizationevents_barnight_robotics
        209046,  # collegeorganizationevents_studygroup_library
        227676,  # collegeorganizationevents_studygroup_library_thursday
        227675,  # collegeorganizationevents_studygroup_library_tuesday
        227677,  # collegeorganizationevents_studygroup_library_wednesday
        224376,  # collegeorganizations_dramanodes_events_debate_showdown
        227626,  # collegeorganizations_dramanodes_events_paintininthepark_monday
        223016,  # collegeorganizations_dramanodes_events_paintininthepark_sunday
        227625,  # collegeorganizations_dramanodes_events_paintininthepark_thursday
        223210,  # collegeorganizations_dramanodes_events_roboticsexhibition
        224755,  # collegeorganizations_dramanodes_events_schoolspirit_party_gamedayparty
        208788,  # collegeorganizations_dramanodes_events_schoolspirit_party_schoolspiritday
        223084,  # collegeorganizations_events_schoolspirit_prank_creativitycelebration
        223142,  # collegeorganizations_events_schoolspirit_prank_gamedayparty
        227928,  # collegeorganizations_events_schoolspirit_prank_gamedayparty_saturday
        187999,  # customholidaydramanode
        199787,  # dialogdramanode_actorcareer_aistaffing_post_generic1
        199788,  # dialogdramanode_actorcareer_aistaffing_post_generic2
        199789,  # dialogdramanode_actorcareer_aistaffing_post_generic3
        199797,  # dialogdramanode_actorcareer_aistaffing_post_gignotscheduled_1
        199798,  # dialogdramanode_actorcareer_aistaffing_post_gignotscheduled_2
        199799,  # dialogdramanode_actorcareer_aistaffing_post_gignotscheduled_3
        199800,  # dialogdramanode_actorcareer_aistaffing_post_gignotscheduled_4
        199802,  # dialogdramanode_actorcareer_aistaffing_post_gignotscheduled_5
        199790,  # dialogdramanode_actorcareer_aistaffing_post_gigscheduled_1
        199791,  # dialogdramanode_actorcareer_aistaffing_post_gigscheduled_2
        199792,  # dialogdramanode_actorcareer_aistaffing_post_gigscheduled_3
        199793,  # dialogdramanode_actorcareer_aistaffing_post_gigscheduled_4
        199794,  # dialogdramanode_actorcareer_aistaffing_post_gigscheduled_5
        199795,  # dialogdramanode_actorcareer_aistaffing_post_gigscheduled_6
        199796,  # dialogdramanode_actorcareer_aistaffing_post_gigscheduled_7
        199281,  # dialogdramanode_actorcareer_gran_auditionfail
        199353,  # dialogdramanode_actorcareer_gran_auditionsuccess
        273857,  # dialogdramanode_askifnewjob
        273860,  # dialogdramanode_askifpromotion
        274844,  # dialogdramanode_asksimtopursuedreamjob_changecareer
        274845,  # dialogdramanode_asksimtopursuedreamjob_nocareerchange
        238028,  # dialogdramanode_batuu_calltoaction
        297476,  # dialogdramanode_bestiephonecall_activities
        297475,  # dialogdramanode_bestiephonecall_intro
        297477,  # dialogdramanode_bestiephonecall_trendi
        258328,  # dialogdramanode_career_interiordecorator_followup_clientcall_note_negative
        258441,  # dialogdramanode_career_interiordecorator_followup_clientcall_note_positive
        255199,  # dialogdramanode_career_interiordecorator_followup_clientcall_referred
        258330,  # dialogdramanode_career_interiordecorator_followup_clientcall_returning_negative
        255190,  # dialogdramanode_career_interiordecorator_followup_clientcall_returning_positive
        260456,  # dialogdramanode_career_interiordecorator_followup_clientcall_returning_positive_postinvite
        258060,  # dialogdramanode_career_interiordecorator_followup_tv_cleanup
        258346,  # dialogdramanode_career_interiordecorator_followup_tv_negative_postshow
        258356,  # dialogdramanode_career_interiordecorator_followup_tv_negative_preshow_mon
        258357,  # dialogdramanode_career_interiordecorator_followup_tv_negative_preshow_sat
        258358,  # dialogdramanode_career_interiordecorator_followup_tv_negative_preshow_sun
        258359,  # dialogdramanode_career_interiordecorator_followup_tv_negative_preshow_thu
        258360,  # dialogdramanode_career_interiordecorator_followup_tv_negative_preshow_tue
        258361,  # dialogdramanode_career_interiordecorator_followup_tv_negative_preshow_wed
        258069,  # dialogdramanode_career_interiordecorator_followup_tv_positive_postshow
        258050,  # dialogdramanode_career_interiordecorator_followup_tv_positive_preshow_mon
        258067,  # dialogdramanode_career_interiordecorator_followup_tv_positive_preshow_sat
        258068,  # dialogdramanode_career_interiordecorator_followup_tv_positive_preshow_sun
        258065,  # dialogdramanode_career_interiordecorator_followup_tv_positive_preshow_thu
        258063,  # dialogdramanode_career_interiordecorator_followup_tv_positive_preshow_tue
        258064,  # dialogdramanode_career_interiordecorator_followup_tv_positive_preshow_wed
        212665,  # dialogdramanode_caughtendangeredfish_fine
        300126,  # dialogdramanode_childhoodfriends_bff
        229458,  # dialogdramanode_collegeorganizations_reminder
        232871,  # dialogdramanode_communitycloseness_borrowsimoleons_followup
        231583,  # dialogdramanode_communitycloseness_borrowsimoleons_initial
        237859,  # dialogdramanode_communitycloseness_civicpolicycall
        231576,  # dialogdramanode_communitycloseness_commitmentissues
        231586,  # dialogdramanode_communitycloseness_dreamofyou
        231577,  # dialogdramanode_communitycloseness_familymatters
        231578,  # dialogdramanode_communitycloseness_feelingblue
        237857,  # dialogdramanode_communitycloseness_friendcrush
        231574,  # dialogdramanode_communitycloseness_gogreen
        231588,  # dialogdramanode_communitycloseness_hotheaded
        231581,  # dialogdramanode_communitycloseness_importantquestions
        231575,  # dialogdramanode_communitycloseness_inheritance
        231584,  # dialogdramanode_communitycloseness_landgrabpower
        237858,  # dialogdramanode_communitycloseness_parentcheckin
        231579,  # dialogdramanode_communitycloseness_prankcall
        237856,  # dialogdramanode_communitycloseness_siblingsimtock
        231582,  # dialogdramanode_communitycloseness_startedmybusiness
        231580,  # dialogdramanode_communitycloseness_telemarketer
        231587,  # dialogdramanode_communitycloseness_themotivegames
        231573,  # dialogdramanode_communitycloseness_thesimulation
        231585,  # dialogdramanode_communitycloseness_wrongnumber
        125714,  # dialogdramanode_condolencesfordeath
        125708,  # dialogdramanode_congratsonbaby
        125667,  # dialogdramanode_congratsonengagement
        125687,  # dialogdramanode_congratsonmarriage
        125699,  # dialogdramanode_congratsonpromotion
        125981,  # dialogdramanode_congratsonsignificantother
        193591,  # dialogdramanode_corporatepartnership
        194066,  # dialogdramanode_corporatepartnership_addtrend1
        194067,  # dialogdramanode_corporatepartnership_addtrend2
        194068,  # dialogdramanode_corporatepartnership_addtrend3
        194069,  # dialogdramanode_corporatepartnership_addtrend4
        194065,  # dialogdramanode_corporatepartnership_addtrend5
        274247,  # dialogdramanode_discussexpandingthefamily_impregnant_targetsim
        274255,  # dialogdramanode_discussexpandingthefamily_impregnant_targetsimpartner
        227277,  # dialogdramanode_e-sports_opportunity
        236677,  # dialogdramanode_entrepreneur_high
        236675,  # dialogdramanode_entrepreneur_low
        236676,  # dialogdramanode_entrepreneur_med
        131898,  # dialogdramanode_experimentalfoodphoto
        322365,  # dialogdramanode_familybirthdaygift
        164890,  # dialogdramanode_familygift
        164962,  # dialogdramanode_fixbadrelationship
        264719,  # dialogdramanode_freesimoleons
        336484,  # dialogdramanode_freesimoleons2
        125785,  # dialogdramanode_goingoutsocials_offlot_breakupsims
        128361,  # dialogdramanode_goingoutsocials_offlot_breakupsims_divorce
        274409,  # dialogdramanode_goingoutsocials_offlot_matchmake_conflictingtraits
        125790,  # dialogdramanode_goingoutsocials_offlot_matchmake_fail
        274507,  # dialogdramanode_goingoutsocials_offlot_matchmake_fail
        125791,  # dialogdramanode_goingoutsocials_offlot_matchmake_inrelationship
        125789,  # dialogdramanode_goingoutsocials_offlot_matchmake_success
        275579,  # dialogdramanode_goingoutsocials_offlot_talkupsim_conflictingtraits
        125788,  # dialogdramanode_goingoutsocials_offlot_talkupsim_fail
        125786,  # dialogdramanode_goingoutsocials_offlot_talkupsim_success
        125784,  # dialogdramanode_goingoutsocials_offlot_trashanothersim
        125724,  # dialogdramanode_gotnewjob
        273861,  # dialogdramanode_gotpromotion
        273858,  # dialogdramanode_gotthejob
        125737,  # dialogdramanode_happybirthday
        282124,  # dialogdramanode_hsexit_graduateearly
        282945,  # dialogdramanode_hsprom_lockerinvite_failure
        282944,  # dialogdramanode_hsprom_lockerinvite_success
        279973,  # dialogdramanode_hsteam_switch_cheerteam
        279974,  # dialogdramanode_hsteam_switch_chessteam
        279978,  # dialogdramanode_hsteam_switch_computerteam
        279976,  # dialogdramanode_hsteam_switch_footballteam
        154433,  # dialogdramanode_introtovampire_call0
        154434,  # dialogdramanode_introtovampire_call1
        154435,  # dialogdramanode_introtovampire_call2
        154436,  # dialogdramanode_introtovampire_call3
        154437,  # dialogdramanode_introtovampire_call4
        308848,  # dialogdramanode_jobloss_joboffer_astronaut
        308849,  # dialogdramanode_jobloss_joboffer_athletic
        308901,  # dialogdramanode_jobloss_joboffer_business
        308931,  # dialogdramanode_jobloss_joboffer_criminal
        308902,  # dialogdramanode_jobloss_joboffer_culinary
        308903,  # dialogdramanode_jobloss_joboffer_entertainer
        308905,  # dialogdramanode_jobloss_joboffer_painter
        308906,  # dialogdramanode_jobloss_joboffer_secretagent
        308908,  # dialogdramanode_jobloss_joboffer_styleinfluencer
        308909,  # dialogdramanode_jobloss_joboffer_techguru
        308910,  # dialogdramanode_jobloss_joboffer_writer
        308156,  # dialogdramanode_jobloss_layoff_freepizza
        308150,  # dialogdramanode_jobloss_layoff_mailedgift
        228261,  # dialogdramanode_lawcareer_judge_bribe
        309387,  # dialogdramanode_lifemilestone_caughtcheatingbysim_exso
        309385,  # dialogdramanode_lifemilestone_caughtcheatingbysim_friend
        309403,  # dialogdramanode_lifemilestone_caughtsimcheating_family
        309388,  # dialogdramanode_lifemilestone_caughtsimcheating_friend
        309381,  # dialogdramanode_lifemilestone_fellinlove_exso
        320401,  # dialogdramanode_lifemilestone_intro
        226813,  # dialogdramanode_loans_firstcall
        226815,  # dialogdramanode_loans_secondcall
        185409,  # dialogdramanode_mailbox_sendgift
        187961,  # dialogdramanode_mailbox_sendgift_toddler
        283646,  # dialogdramanode_moveout
        269971,  # dialogdramanode_musicfestival2021_closebusinesses
        269980,  # dialogdramanode_musicfestival2021_npc_phone_call
        270127,  # dialogdramanode_musicfestival2021_npc_phone_call_return
        269931,  # dialogdramanode_musicfestival2021_ticketgift
        274053,  # dialogdramanode_neighborrelphonecall_followup_friendly_furtherfriendship
        274055,  # dialogdramanode_neighborrelphonecall_followup_friendly_nofurtherfriendship
        279079,  # dialogdramanode_neighborrelphonecall_followup_romantic_furtherrelationship
        279080,  # dialogdramanode_neighborrelphonecall_followup_romantic_nofurtherrelationship
        273994,  # dialogdramanode_neighborrelphonecall_initial_friendly
        279078,  # dialogdramanode_neighborrelphonecall_initial_romantic
        126021,  # dialogdramanode_newenemy
        125996,  # dialogdramanode_newfriend
        282997,  # dialogdramanode_openablewindow_collegeparty
        283434,  # dialogdramanode_openablewindow_hangout
        283433,  # dialogdramanode_openablewindow_loitering
        283432,  # dialogdramanode_openablewindow_popconcert
        283431,  # dialogdramanode_openablewindow_rmovie
        283430,  # dialogdramanode_openablewindow_schoolgame
        283429,  # dialogdramanode_openablewindow_sleepover
        124845,  # dialogdramanode_phone_invitenpcover
        195441,  # dialogdramanode_quirk_publicnumber_angry
        195442,  # dialogdramanode_quirk_publicnumber_embarrassed
        195445,  # dialogdramanode_quirk_publicnumber_flirty
        202591,  # dialogdramanode_quirk_publicnumber_flirty_t2t
        195295,  # dialogdramanode_quirk_publicnumber_happy
        202592,  # dialogdramanode_quirk_publicnumber_happy_t2t
        195444,  # dialogdramanode_quirk_publicnumber_inspired
        195443,  # dialogdramanode_quirk_publicnumber_sad
        195446,  # dialogdramanode_quirk_publicnumber_stressed
        202593,  # dialogdramanode_quirk_publicnumber_stressed_t2t
        270375,  # dialogdramanode_requiredingredients_starving
        221721,  # dialogdramanode_roommatenpc_lockedout_call
        339176,  # dialogdramanode_scenario_inheritance_grandma_1a
        339177,  # dialogdramanode_scenario_inheritance_grandma_1b_talk
        339186,  # dialogdramanode_scenario_inheritance_grandma_1c_donate
        339178,  # dialogdramanode_scenario_inheritance_grandma_2a
        339179,  # dialogdramanode_scenario_inheritance_grandma_2b_job
        339180,  # dialogdramanode_scenario_inheritance_grandma_2c_healedsentiment
        339181,  # dialogdramanode_scenario_inheritance_grandma_2d_burninheritance
        339182,  # dialogdramanode_scenario_inheritance_grandma_3a
        339183,  # dialogdramanode_scenario_inheritance_grandma_3a_ghostinvited
        339184,  # dialogdramanode_scenario_inheritance_grandma_3b
        339185,  # dialogdramanode_scenario_inheritance_grandma_3b_ghostinvited
        297048,  # dialogdramanode_scenario_newintown_phas3bintro
        301256,  # dialogdramanode_scenario_newintown_phase1_intro
        297042,  # dialogdramanode_scenario_newintown_phase2_intro
        297045,  # dialogdramanode_scenario_newintown_phase3aintro
        299973,  # dialogdramanode_scenario_newintown_phase4_intro
        301769,  # dialogdramanode_scenario_newintown_phase4_newacquaintancecaller_friendbar
        301763,  # dialogdramanode_scenario_newintown_phase4_newacquaintancecaller_friendgym
        301771,  # dialogdramanode_scenario_newintown_phase4_newacquaintancecaller_romancebar
        300774,  # dialogdramanode_scenario_newintown_phase4_nextphasephonecall
        298602,  # dialogdramanode_scenario_newintown_phase5_intro
        294373,  # dialogdramanode_scenario_parentingpredicament_principal_phase1
        297657,  # dialogdramanode_scenario_parentingpredicament_principal_phase2
        298530,  # dialogdramanode_scenario_parentingpredicament_principal_phase3
        298531,  # dialogdramanode_scenario_parentingpredicament_principal_phase4_teenager
        297841,  # dialogdramanode_scenario_stuckintheirshadow_1managercall
        294839,  # dialogdramanode_scenario_stuckintheirshadow_1rivalcall_intro
        299009,  # dialogdramanode_scenario_stuckintheirshadow_1rivalcall_intro_ifmissed
        296532,  # dialogdramanode_scenario_stuckintheirshadow_2optionalpto
        296656,  # dialogdramanode_scenario_stuckintheirshadow_3aliensecret
        296655,  # dialogdramanode_scenario_stuckintheirshadow_3inviteorkick
        295441,  # dialogdramanode_scenario_stuckintheirshadow_3rival_fired
        299014,  # dialogdramanode_scenario_stuckintheirshadow_3rival_fired_ifmissed
        302208,  # dialogdramanode_scenario_stuckintheirshadow_4aastronautoffer
        300652,  # dialogdramanode_scenario_stuckintheirshadow_4apostcard
        296657,  # dialogdramanode_scenario_stuckintheirshadow_4arivalnewjob
        296524,  # dialogdramanode_scenario_stuckintheirshadow_4arivalpurchases
        296661,  # dialogdramanode_scenario_stuckintheirshadow_4bindies
        296660,  # dialogdramanode_scenario_stuckintheirshadow_4bspaceprint
        302204,  # dialogdramanode_scenario_stuckintheirshadow_rival_4aalienpet
        227350,  # dialogdramanode_scholarshipinfo
        187443,  # dialogdramanode_sendforgedbreakupletter_brokenup
        187462,  # dialogdramanode_sendforgedbreakupletter_divorced
        187763,  # dialogdramanode_sendforgedbreakupletter_foundout
        187759,  # dialogdramanode_sendforgedbreakupletter_hadfight
        299210,  # dialogdramanode_socialmediaposttns
        167172,  # dialogdramanode_sp11_intro
        280605,  # dialogdramanode_story_progression_childrenstories_impregnant
        184953,  # dialogdramanode_surpriseholiday_lottery_wininvite
        129583,  # dialogdramanode_test_node
        212441,  # dialogdramanode_turtlehatching_reminder
        224238,  # dialogdramanode_university_caughtcheating_homework
        224237,  # dialogdramanode_university_caughtcheating_termpaper
        229272,  # dialogdramanode_university_enrollmentinfo
        230262,  # dialogdramanode_university_enrollmentinfo_permanentcooldown
        224020,  # dialogdramanode_university_finalexam_caughtcheating
        226559,  # dialogdramanode_university_soccerteam_prosports
        228041,  # dialogdramanode_university_sportsarena_gamedayreminder_esports_arts
        228042,  # dialogdramanode_university_sportsarena_gamedayreminder_esports_science
        228039,  # dialogdramanode_university_sportsarena_gamedayreminder_football_arts
        228040,  # dialogdramanode_university_sportsarena_gamedayreminder_football_science
        268599,  # dialogdramanode_villagerhelp_discoverytracker_npcvillager_day2
        268608,  # dialogdramanode_villagerhelp_discoverytracker_npcvillager_day2_tns
        268600,  # dialogdramanode_villagerhelp_discoverytracker_npcvillager_day4
        268601,  # dialogdramanode_villagerhelp_discoverytracker_npcvillager_day8
        269314,  # dialogdramanode_villagerhelp_discoverytracker_npcvillager_day8_call
        268972,  # dialogdramanode_villagerhelp_discoverytracker_npcvillager_pending
        268602,  # dialogdramanode_villagerhelp_discoverytracker_offerhelp_day1
        268607,  # dialogdramanode_villagerhelp_discoverytracker_offerhelp_day1_villagertns
        268603,  # dialogdramanode_villagerhelp_discoverytracker_offerhelp_day3
        268612,  # dialogdramanode_villagerhelp_discoverytracker_offerhelp_day3_simtns
        268604,  # dialogdramanode_villagerhelp_discoverytracker_offerhelp_day7
        125807,  # dialogdramanode_welcometoclub
        294413,  # dialogdramanode_werewolf_joinpackrequest
        291166,  # dialogdramanode_werewolf_text
        289611,  # dialogdramanode_werewolfpack_alliancefeud
        294426,  # dialogdramanode_werewolfpackbenefits_packatreats
        294429,  # dialogdramanode_werewolfpackbenefits_packbtreats
        298901,  # dialogdramanode_werewolfrepairman
        198178,  # dramanode_actorcareer_performancefeedback_estellegable_commercial_high
        198135,  # dramanode_actorcareer_performancefeedback_estellegable_commercial_low
        198165,  # dramanode_actorcareer_performancefeedback_estellegable_commercial_med
        198190,  # dramanode_actorcareer_performancefeedback_estellegable_movie_high
        198188,  # dramanode_actorcareer_performancefeedback_estellegable_movie_low
        198189,  # dramanode_actorcareer_performancefeedback_estellegable_movie_med
        198187,  # dramanode_actorcareer_performancefeedback_estellegable_tvhigh_high
        198185,  # dramanode_actorcareer_performancefeedback_estellegable_tvhigh_low
        198186,  # dramanode_actorcareer_performancefeedback_estellegable_tvhigh_med
        198184,  # dramanode_actorcareer_performancefeedback_estellegable_tvlow_high
        198182,  # dramanode_actorcareer_performancefeedback_estellegable_tvlow_low
        198183,  # dramanode_actorcareer_performancefeedback_estellegable_tvlow_med
        198179,  # dramanode_actorcareer_performancefeedback_hangten_commercial_high
        198162,  # dramanode_actorcareer_performancefeedback_hangten_commercial_low
        198166,  # dramanode_actorcareer_performancefeedback_hangten_commercial_med
        198199,  # dramanode_actorcareer_performancefeedback_hangten_movie_high
        198197,  # dramanode_actorcareer_performancefeedback_hangten_movie_low
        198198,  # dramanode_actorcareer_performancefeedback_hangten_movie_med
        198196,  # dramanode_actorcareer_performancefeedback_hangten_tvhigh_high
        198194,  # dramanode_actorcareer_performancefeedback_hangten_tvhigh_low
        198195,  # dramanode_actorcareer_performancefeedback_hangten_tvhigh_med
        198193,  # dramanode_actorcareer_performancefeedback_hangten_tvlow_high
        198191,  # dramanode_actorcareer_performancefeedback_hangten_tvlow_low
        198192,  # dramanode_actorcareer_performancefeedback_hangten_tvlow_med
        198180,  # dramanode_actorcareer_performancefeedback_seriousbusiness_commercial_high
        198164,  # dramanode_actorcareer_performancefeedback_seriousbusiness_commercial_low
        198167,  # dramanode_actorcareer_performancefeedback_seriousbusiness_commercial_med
        198208,  # dramanode_actorcareer_performancefeedback_seriousbusiness_movie_high
        198206,  # dramanode_actorcareer_performancefeedback_seriousbusiness_movie_low
        198207,  # dramanode_actorcareer_performancefeedback_seriousbusiness_movie_med
        198205,  # dramanode_actorcareer_performancefeedback_seriousbusiness_tvhigh_high
        198203,  # dramanode_actorcareer_performancefeedback_seriousbusiness_tvhigh_low
        198204,  # dramanode_actorcareer_performancefeedback_seriousbusiness_tvhigh_med
        198202,  # dramanode_actorcareer_performancefeedback_seriousbusiness_tvlow_high
        198200,  # dramanode_actorcareer_performancefeedback_seriousbusiness_tvlow_low
        198201,  # dramanode_actorcareer_performancefeedback_seriousbusiness_tvlow_med
        198181,  # dramanode_actorcareer_performancefeedback_wearereallyhuman_commercial_high
        198163,  # dramanode_actorcareer_performancefeedback_wearereallyhuman_commercial_low
        198168,  # dramanode_actorcareer_performancefeedback_wearereallyhuman_commercial_med
        198217,  # dramanode_actorcareer_performancefeedback_wearereallyhuman_movie_high
        198215,  # dramanode_actorcareer_performancefeedback_wearereallyhuman_movie_low
        198216,  # dramanode_actorcareer_performancefeedback_wearereallyhuman_movie_med
        198214,  # dramanode_actorcareer_performancefeedback_wearereallyhuman_tvhigh_high
        198212,  # dramanode_actorcareer_performancefeedback_wearereallyhuman_tvhigh_low
        198213,  # dramanode_actorcareer_performancefeedback_wearereallyhuman_tvhigh_med
        198211,  # dramanode_actorcareer_performancefeedback_wearereallyhuman_tvlow_high
        198209,  # dramanode_actorcareer_performancefeedback_wearereallyhuman_tvlow_low
        198210,  # dramanode_actorcareer_performancefeedback_wearereallyhuman_tvlow_med
        127383,  # dramanode_barnights_aliensnight
        127382,  # dramanode_barnights_bearnight
        127384,  # dramanode_barnights_ghostsnight
        127387,  # dramanode_barnights_guysnight
        130364,  # dramanode_barnights_knightnight
        127385,  # dramanode_barnights_ladiesnight
        127386,  # dramanode_barnights_singlesnight
        142869,  # dramanode_cityinvites_rabbithole_circus
        142870,  # dramanode_cityinvites_rabbithole_concert
        142806,  # dramanode_cityinvites_rabbithole_opera
        142871,  # dramanode_cityinvites_rabbithole_theater
        268796,  # dramanode_donothing_foxsupression
        281031,  # dramanode_highschool_active_calendar_careerday
        281032,  # dramanode_highschool_active_calendar_exam
        283685,  # dramanode_highschool_active_debug_careerday
        283688,  # dramanode_highschool_active_debug_exam
        283656,  # dramanode_highschool_active_debug_firedrill
        283689,  # dramanode_highschool_active_debug_schoolfight
        283713,  # dramanode_highschool_active_firedrill
        288769,  # dramanode_highschool_active_nobackgroundevent
        283751,  # dramanode_highschool_active_schoolfight
        268626,  # dramanode_mayor_jam
        194754,  # dramanode_musicproductionstation_signwithdinkybeats
        194756,  # dramanode_musicproductionstation_signwithmaxismusicmachine
        194755,  # dramanode_musicproductionstation_signwithnewtastemakers
        195052,  # dramanode_musicproductionstation_warningwithdinkybeats
        195053,  # dramanode_musicproductionstation_warningwithmaxismusicmachine
        195054,  # dramanode_musicproductionstation_warningwithnewtastemakers
        128981,  # dramanode_npc_invite_sadtext
        127297,  # dramanode_npcinvite_angrytext
        124496,  # dramanode_npcinvite_birthdayparty
        258332,  # dramanode_npcinvite_career_interiordecorator_followup_clientcall
        125893,  # dramanode_npcinvite_celebratepromotion
        126452,  # dramanode_npcinvite_clubfriends
        137943,  # dramanode_npcinvite_criticcareer_localhangout_bar
        137944,  # dramanode_npcinvite_criticcareer_localhangout_club
        137934,  # dramanode_npcinvite_criticcareer_localhangout_museum
        140065,  # dramanode_npcinvite_criticcareer_localhangout_restaurant
        124495,  # dramanode_npcinvite_date
        125853,  # dramanode_npcinvite_date_goingoutsocials
        190853,  # dramanode_npcinvite_date_holiday
        297065,  # dramanode_npcinvite_date_newintown_phase4
        196010,  # dramanode_npcinvite_date_reputation_bad
        196009,  # dramanode_npcinvite_date_reputation_good
        274689,  # dramanode_npcinvite_discussexpandingthefamily_hadbaby_targetsim
        274690,  # dramanode_npcinvite_discussexpandingthefamily_hadbaby_targetsimpartner
        127220,  # dramanode_npcinvite_energizedtext
        127274,  # dramanode_npcinvite_flirtytext
        125870,  # dramanode_npcinvite_godancing
        127430,  # dramanode_npcinvite_godancing_bluffs
        127431,  # dramanode_npcinvite_godancing_chalet
        127429,  # dramanode_npcinvite_godancing_ruins
        127241,  # dramanode_npcinvite_happytext
        218351,  # dramanode_npcinvite_magicduel_challenge
        280278,  # dramanode_npcinvite_movein
        124497,  # dramanode_npcinvite_playdate
        127263,  # dramanode_npcinvite_playfultext
        125946,  # dramanode_npcinvite_playhooky
        134418,  # dramanode_npcinvite_restaurant_burythehatchet
        134428,  # dramanode_npcinvite_restaurant_condolences
        134420,  # dramanode_npcinvite_restaurant_congratsonthepromotion
        134434,  # dramanode_npcinvite_restaurant_enemydate
        134325,  # dramanode_npcinvite_restaurant_standard
        134439,  # dramanode_npcinvite_restaurant_standarddate
        138192,  # dramanode_npcinvite_restaurant_standarddate_firstweek
        280463,  # dramanode_npcinvite_story_progression_childrenstories_adoptedbaby
        280461,  # dramanode_npcinvite_story_progression_childrenstories_adoptedcat
        280465,  # dramanode_npcinvite_story_progression_childrenstories_adoptedchild
        280462,  # dramanode_npcinvite_story_progression_childrenstories_adopteddog
        338187,  # dramanode_npcinvite_story_progression_childrenstories_adoptedhorse
        280464,  # dramanode_npcinvite_story_progression_childrenstories_adoptedtoddler
        280459,  # dramanode_npcinvite_story_progression_childrenstories_hadbaby
        128959,  # dramanode_phone_npcinvite
        165263,  # dramanode_phone_npcinvite_family
        165280,  # dramanode_phone_npcinvite_family_venue
        183089,  # dramanode_premadeholiday_surprise_battleroyale
        183097,  # dramanode_premadeholiday_surprise_discountday
        183096,  # dramanode_premadeholiday_surprise_lottery
        183095,  # dramanode_premadeholiday_surprise_nightonthetown
        183094,  # dramanode_premadeholiday_surprise_pirateday
        183093,  # dramanode_premadeholiday_surprise_prankday
        183092,  # dramanode_premadeholiday_surprise_skillday
        183090,  # dramanode_premadeholiday_surprise_tvpremiere
        196074,  # dramanode_reputation_bad_addnewfriend
        202834,  # dramanode_reputation_bad_addnewfriend_child
        195694,  # dramanode_reputation_bad_career_criminal
        195215,  # dramanode_reputation_bad_caughtcheating
        195216,  # dramanode_reputation_bad_caughtstealing
        195221,  # dramanode_reputation_bad_caughttakingblood
        201191,  # dramanode_reputation_bad_childtakenaway
        195218,  # dramanode_reputation_bad_despised
        195217,  # dramanode_reputation_bad_disliked
        195214,  # dramanode_reputation_bad_fighting
        196093,  # dramanode_reputation_bad_illgottengains
        195222,  # dramanode_reputation_bad_neighborhoodhivemind
        196075,  # dramanode_reputation_bad_newfriendintro
        202836,  # dramanode_reputation_bad_newfriendintro_child
        195219,  # dramanode_reputation_bad_pettakenaway
        195213,  # dramanode_reputation_bad_pickpocket
        195736,  # dramanode_reputation_good_addnewfriend
        202838,  # dramanode_reputation_good_addnewfriend_child
        202884,  # dramanode_reputation_good_career_actor
        195604,  # dramanode_reputation_good_career_astronaut
        195606,  # dramanode_reputation_good_career_athletic
        195607,  # dramanode_reputation_good_career_business
        195608,  # dramanode_reputation_good_career_culinary
        195609,  # dramanode_reputation_good_career_entertainer
        195637,  # dramanode_reputation_good_career_gardener
        195611,  # dramanode_reputation_good_career_painter
        195632,  # dramanode_reputation_good_career_secretagent
        202887,  # dramanode_reputation_good_career_socialmedia
        202886,  # dramanode_reputation_good_career_styleinfluencer
        195633,  # dramanode_reputation_good_career_techguru
        195636,  # dramanode_reputation_good_career_writer
        195209,  # dramanode_reputation_good_donate
        196252,  # dramanode_reputation_good_donatedtocharity
        193123,  # dramanode_reputation_good_friends
        195211,  # dramanode_reputation_good_happytown
        195740,  # dramanode_reputation_good_newfriendintro
        202840,  # dramanode_reputation_good_newfriendintro_child
        195210,  # dramanode_reputation_good_throwcharitybenefitparty
        297063,  # dramanode_scenario_npcinvite_newintown_phase4_lounge
        152037,  # dramanode_vampirecreation_invitetotransform_hashome
        152316,  # dramanode_vampirecreation_invitetotransform_nohome
        155260,  # dramanode_vampires_initial_vampireintroduction
        259971,  # festivalcontestdramanode_villagefair_chickenegg
        259969,  # festivalcontestdramanode_villagefair_cowmilk
        259973,  # festivalcontestdramanode_villagefair_giantcroppie
        259970,  # festivalcontestdramanode_villagefair_llamawool
        259972,  # festivalcontestdramanode_villagefair_normalcroppie
        265007,  # festivalcontestsubdramanode_villagefair_egg
        265014,  # festivalcontestsubdramanode_villagefair_milk
        265013,  # festivalcontestsubdramanode_villagefair_pie
        265012,  # festivalcontestsubdramanode_villagefair_wool
        140083,  # festivaldramanode_blossomfestival
        140085,  # festivaldramanode_fleamarket
        140082,  # festivaldramanode_foodfestival
        140084,  # festivaldramanode_lampfestival
        141200,  # festivaldramanode_logicfair
        269621,  # festivaldramanode_musicfestival
        246532,  # festivaldramanodes_lightfestival
        246534,  # festivaldramanodes_snowfestival
        246533,  # festivaldramanodes_youthfestival
        279912,  # graduationvenueeventdramanode_graduation
        281853,  # highschoolfestival_sciencefair_chess
        281854,  # highschoolfestival_sciencefair_computer
        281852,  # highschoolfestival_sportsday_cheer
        281849,  # highschoolfestival_sportsday_football
        183110,  # holidaydramanode_mainholidays_harvestfest
        183108,  # holidaydramanode_mainholidays_loveday
        183109,  # holidaydramanode_mainholidays_newyears
        183107,  # holidaydramanode_mainholidays_winterfest
        208690,  # islandevents_large_dramanode_fishingcompetition
        205654,  # islandevents_large_dramanode_islandcelebration
        205653,  # islandevents_large_dramanode_turtlehatching
        205593,  # islandevents_small_dramanode_beachbonfire
        205744,  # islandevents_small_dramanode_familyfunday
        205594,  # islandevents_small_dramanode_flowersandmusic
        205591,  # islandevents_small_dramanode_townbbq
        204566,  # islandevents_small_dramanode_townpotluck
        184762,  # lotterydramanode_holidaylottery
        197145,  # loungevenueevents_awardceremony
        197146,  # loungevenueevents_meetacelebrity_monday
        197150,  # loungevenueevents_meetacelebrity_wednesday
        197144,  # loungevenueevents_openmic_friday
        197151,  # loungevenueevents_openmic_saturday
        142815,  # npcinvite_cityinvites_apartmentinvites_fromfriend
        149698,  # npcinvite_cityinvites_festivals_all_buyashirt
        143028,  # npcinvite_cityinvites_festivals_blossom_drinktea
        143029,  # npcinvite_cityinvites_festivals_blossom_kiss
        180376,  # npcinvite_cityinvites_festivals_blossom_kiss_teen
        143038,  # npcinvite_cityinvites_festivals_blossom_meetpeople
        143039,  # npcinvite_cityinvites_festivals_blossom_paint
        143040,  # npcinvite_cityinvites_festivals_blossom_throwpetals
        155679,  # npcinvite_cityinvites_festivals_buyashirt_food
        155681,  # npcinvite_cityinvites_festivals_buyashirt_logic
        143041,  # npcinvite_cityinvites_festivals_fleamarket_buysomething
        143042,  # npcinvite_cityinvites_festivals_fleamarket_haggle
        143043,  # npcinvite_cityinvites_festivals_fleamarket_watchperformer
        148689,  # npcinvite_cityinvites_festivals_food_blowbubbles
        143044,  # npcinvite_cityinvites_festivals_food_buyingredients
        143046,  # npcinvite_cityinvites_festivals_food_discusslocalcuisine
        143047,  # npcinvite_cityinvites_festivals_food_eatburrito
        143030,  # npcinvite_cityinvites_festivals_food_eatspicy
        143048,  # npcinvite_cityinvites_festivals_food_harvest
        143049,  # npcinvite_cityinvites_festivals_food_sample
        149398,  # npcinvite_cityinvites_festivals_food_trychopsticksfoods
        143050,  # npcinvite_cityinvites_festivals_lamp_buyshirt
        143051,  # npcinvite_cityinvites_festivals_lamp_drinktea
        143052,  # npcinvite_cityinvites_festivals_lamp_eatfood
        149699,  # npcinvite_cityinvites_festivals_lamp_lightfireworks
        143053,  # npcinvite_cityinvites_festivals_lamp_watchfireworks
        143054,  # npcinvite_cityinvites_festivals_logic_buildrocket
        143055,  # npcinvite_cityinvites_festivals_logic_motiongaming
        143031,  # npcinvite_cityinvites_festivals_logic_observatory
        143032,  # npcinvite_cityinvites_festivals_logic_participateincontest
        143033,  # npcinvite_cityinvites_festivals_logic_program
        143034,  # npcinvite_cityinvites_venueinvites_bar
        143035,  # npcinvite_cityinvites_venueinvites_gym
        143036,  # npcinvite_cityinvites_venueinvites_karaoke
        143037,  # npcinvite_cityinvites_venueinvites_park
        200710,  # npcinvite_dramanode_situation_reputation_charity
        201268,  # npcinvite_dramanode_situation_reputation_lampoonparty
        198598,  # npcinvite_loungeevent_meetacelebrity
        198599,  # npcinvite_loungeevent_openmic
        283489,  # npcinvitesituationdramanode_hsprom_postpromdramanode
        195149,  # pickerdramanode_actorcareer_commercial_hospital
        199172,  # pickerdramanode_actorcareer_commercial_hospital_aistaffing
        199226,  # pickerdramanode_actorcareer_commercial_hospital_gran
        199198,  # pickerdramanode_actorcareer_commercial_hospital_wellsuited
        196249,  # pickerdramanode_actorcareer_commercial_housenice
        199173,  # pickerdramanode_actorcareer_commercial_housenice_aistaffing
        199227,  # pickerdramanode_actorcareer_commercial_housenice_gran
        199199,  # pickerdramanode_actorcareer_commercial_housenice_wellsuited
        195148,  # pickerdramanode_actorcareer_commercial_kids
        199174,  # pickerdramanode_actorcareer_commercial_kids_aistaffing
        199228,  # pickerdramanode_actorcareer_commercial_kids_gran
        199200,  # pickerdramanode_actorcareer_commercial_kids_wellsuited
        195125,  # pickerdramanode_actorcareer_commercial_pirate
        199175,  # pickerdramanode_actorcareer_commercial_pirate_aistaffing
        199229,  # pickerdramanode_actorcareer_commercial_pirate_gran
        199201,  # pickerdramanode_actorcareer_commercial_pirate_wellsuited
        195151,  # pickerdramanode_actorcareer_commercial_western
        199176,  # pickerdramanode_actorcareer_commercial_western_aistaffing
        199230,  # pickerdramanode_actorcareer_commercial_western_gran
        199202,  # pickerdramanode_actorcareer_commercial_western_wellsuited
        195174,  # pickerdramanode_actorcareer_film_dancingintherain
        199178,  # pickerdramanode_actorcareer_film_dancingintherain_aistaffing
        199232,  # pickerdramanode_actorcareer_film_dancingintherain_gran
        199204,  # pickerdramanode_actorcareer_film_dancingintherain_wellsuited
        195173,  # pickerdramanode_actorcareer_film_medieval
        199179,  # pickerdramanode_actorcareer_film_medieval_aistaffing
        199233,  # pickerdramanode_actorcareer_film_medieval_gran
        199205,  # pickerdramanode_actorcareer_film_medieval_wellsuited
        195172,  # pickerdramanode_actorcareer_film_pirate
        199180,  # pickerdramanode_actorcareer_film_pirate_aistaffing
        199234,  # pickerdramanode_actorcareer_film_pirate_gran
        199206,  # pickerdramanode_actorcareer_film_pirate_wellsuited
        195170,  # pickerdramanode_actorcareer_film_superhero
        199181,  # pickerdramanode_actorcareer_film_superhero_aistaffing
        199235,  # pickerdramanode_actorcareer_film_superhero_gran
        199207,  # pickerdramanode_actorcareer_film_superhero_wellsuited
        195171,  # pickerdramanode_actorcareer_film_victorian
        199182,  # pickerdramanode_actorcareer_film_victorian_aistaffing
        199236,  # pickerdramanode_actorcareer_film_victorian_gran
        199208,  # pickerdramanode_actorcareer_film_victorian_wellsuited
        195175,  # pickerdramanode_actorcareer_film_western
        199183,  # pickerdramanode_actorcareer_film_western_aistaffing
        199237,  # pickerdramanode_actorcareer_film_western_gran
        199209,  # pickerdramanode_actorcareer_film_western_wellsuited
        195164,  # pickerdramanode_actorcareer_highbudgettv_apocalypse
        199185,  # pickerdramanode_actorcareer_highbudgettv_apocalypse_aistaffing
        199239,  # pickerdramanode_actorcareer_highbudgettv_apocalypse_gran
        199211,  # pickerdramanode_actorcareer_highbudgettv_apocalypse_wellsuited
        195166,  # pickerdramanode_actorcareer_highbudgettv_hopsital
        199186,  # pickerdramanode_actorcareer_highbudgettv_hopsital_aistaffing
        199240,  # pickerdramanode_actorcareer_highbudgettv_hopsital_gran
        199212,  # pickerdramanode_actorcareer_highbudgettv_hopsital_wellsuited
        195165,  # pickerdramanode_actorcareer_highbudgettv_police
        199187,  # pickerdramanode_actorcareer_highbudgettv_police_aistaffing
        199242,  # pickerdramanode_actorcareer_highbudgettv_police_gran
        199213,  # pickerdramanode_actorcareer_highbudgettv_police_wellsuited
        195167,  # pickerdramanode_actorcareer_highbudgettv_victorian
        199188,  # pickerdramanode_actorcareer_highbudgettv_victorian_aistaffing
        199243,  # pickerdramanode_actorcareer_highbudgettv_victorian_gran
        199214,  # pickerdramanode_actorcareer_highbudgettv_victorian_wellsuited
        195168,  # pickerdramanode_actorcareer_highbudgettv_western
        199189,  # pickerdramanode_actorcareer_highbudgettv_western_aistaffing
        199244,  # pickerdramanode_actorcareer_highbudgettv_western_gran
        199215,  # pickerdramanode_actorcareer_highbudgettv_western_wellsuited
        195156,  # pickerdramanode_actorcareer_lowbudgettv_houselow
        199191,  # pickerdramanode_actorcareer_lowbudgettv_houselow_aistaffing
        199246,  # pickerdramanode_actorcareer_lowbudgettv_houselow_gran
        199217,  # pickerdramanode_actorcareer_lowbudgettv_houselow_wellsuited
        195154,  # pickerdramanode_actorcareer_lowbudgettv_housenice
        199192,  # pickerdramanode_actorcareer_lowbudgettv_housenice_aistaffing
        199247,  # pickerdramanode_actorcareer_lowbudgettv_housenice_gran
        199218,  # pickerdramanode_actorcareer_lowbudgettv_housenice_wellsuited
        195157,  # pickerdramanode_actorcareer_lowbudgettv_kids
        199193,  # pickerdramanode_actorcareer_lowbudgettv_kids_aistaffing
        199248,  # pickerdramanode_actorcareer_lowbudgettv_kids_gran
        199219,  # pickerdramanode_actorcareer_lowbudgettv_kids_wellsuited
        195155,  # pickerdramanode_actorcareer_lowbudgettv_pirate
        199194,  # pickerdramanode_actorcareer_lowbudgettv_pirate_aistaffing
        199249,  # pickerdramanode_actorcareer_lowbudgettv_pirate_gran
        199220,  # pickerdramanode_actorcareer_lowbudgettv_pirate_wellsuited
        195153,  # pickerdramanode_actorcareer_lowbudgettv_western
        199195,  # pickerdramanode_actorcareer_lowbudgettv_western_aistaffing
        199250,  # pickerdramanode_actorcareer_lowbudgettv_western_gran
        199221,  # pickerdramanode_actorcareer_lowbudgettv_western_wellsuited
        258886,  # pickerdramanode_career_interiordecorator_level_addition
        267253,  # pickerdramanode_career_interiordecorator_level_addition_famous_high_fame
        267252,  # pickerdramanode_career_interiordecorator_level_addition_famous_low_fame
        267365,  # pickerdramanode_career_interiordecorator_level_addition_high
        267658,  # pickerdramanode_career_interiordecorator_level_addition_mancave
        267659,  # pickerdramanode_career_interiordecorator_level_addition_shelevel
        264792,  # pickerdramanode_career_interiordecorator_level_addition_skill_level_fitness_basement
        264789,  # pickerdramanode_career_interiordecorator_level_addition_top_floor_family_room
        266257,  # pickerdramanode_career_interiordecorator_level_addition_top_floor_photography
        267004,  # pickerdramanode_career_interiordecorator_level_addition_top_floor_tile_restriction_office_bath
        258888,  # pickerdramanode_career_interiordecorator_level_renovation
        259801,  # pickerdramanode_career_interiordecorator_level_renovation_commercial_bar
        267247,  # pickerdramanode_career_interiordecorator_level_renovation_commercial_cafe
        261820,  # pickerdramanode_career_interiordecorator_level_renovation_commercial_club
        261821,  # pickerdramanode_career_interiordecorator_level_renovation_commercial_gym
        261822,  # pickerdramanode_career_interiordecorator_level_renovation_commercial_library
        261819,  # pickerdramanode_career_interiordecorator_level_renovation_commercial_lounge
        267246,  # pickerdramanode_career_interiordecorator_level_renovation_commercial_vet_clinic
        267372,  # pickerdramanode_career_interiordecorator_level_renovation_high
        260880,  # pickerdramanode_career_interiordecorator_level_renovation_kitchen
        267666,  # pickerdramanode_career_interiordecorator_level_renovation_living
        261148,  # pickerdramanode_career_interiordecorator_level_renovation_living_kitchen
        261392,  # pickerdramanode_career_interiordecorator_level_renovation_sponsored_library
        266367,  # pickerdramanode_career_interiordecorator_level_renovation_sponsored_museum
        258435,  # pickerdramanode_career_interiordecorator_room_addition
        267679,  # pickerdramanode_career_interiordecorator_room_addition_commercial_arcade
        267677,  # pickerdramanode_career_interiordecorator_room_addition_commercial_bathrooms
        267374,  # pickerdramanode_career_interiordecorator_room_addition_high
        266522,  # pickerdramanode_career_interiordecorator_room_addition_inlaw_unit
        261125,  # pickerdramanode_career_interiordecorator_room_addition_nursery
        260553,  # pickerdramanode_career_interiordecorator_room_addition_skill_room_fitness
        260779,  # pickerdramanode_career_interiordecorator_room_addition_skill_room_gardening
        260755,  # pickerdramanode_career_interiordecorator_room_addition_skill_room_guitar
        260719,  # pickerdramanode_career_interiordecorator_room_addition_skill_room_handiness
        260768,  # pickerdramanode_career_interiordecorator_room_addition_skill_room_mixology
        259237,  # pickerdramanode_career_interiordecorator_room_addition_skill_room_painting
        260554,  # pickerdramanode_career_interiordecorator_room_addition_skill_room_photography
        260762,  # pickerdramanode_career_interiordecorator_room_addition_skill_room_piano
        260713,  # pickerdramanode_career_interiordecorator_room_addition_skill_room_programming
        260730,  # pickerdramanode_career_interiordecorator_room_addition_skill_room_videogaming
        267034,  # pickerdramanode_career_interiordecorator_room_addition_walkin_closet
        258428,  # pickerdramanode_career_interiordecorator_room_renovation
        263108,  # pickerdramanode_career_interiordecorator_room_renovations_bathroom
        263107,  # pickerdramanode_career_interiordecorator_room_renovations_bedroom
        261203,  # pickerdramanode_career_interiordecorator_room_renovations_followup_negative
        261202,  # pickerdramanode_career_interiordecorator_room_renovations_followup_positive
        261201,  # pickerdramanode_career_interiordecorator_room_renovations_followup_referred
        267377,  # pickerdramanode_career_interiordecorator_room_renovations_high
        263545,  # pickerdramanode_career_interiordecorator_room_renovations_kidsroom
        263106,  # pickerdramanode_career_interiordecorator_room_renovations_kitchen
        266622,  # pickerdramanode_career_interiordecorator_room_renovations_office
        267027,  # pickerdramanode_career_interiordecorator_room_renovations_sponsored_bar
        266369,  # pickerdramanode_career_interiordecorator_room_renovations_sponsored_gym
        267007,  # pickerdramanode_career_interiordecorator_room_renovations_walkin_closet
        207444,  # pickerdramanode_freelancer_artist_art_teacher
        207493,  # pickerdramanode_freelancer_artist_art_teacher_2
        207495,  # pickerdramanode_freelancer_artist_art_teacher_3
        207446,  # pickerdramanode_freelancer_artist_character_concept
        207525,  # pickerdramanode_freelancer_artist_character_concept_2
        207526,  # pickerdramanode_freelancer_artist_character_concept_3
        207447,  # pickerdramanode_freelancer_artist_environment_concept
        207528,  # pickerdramanode_freelancer_artist_environment_concept_2
        207529,  # pickerdramanode_freelancer_artist_environment_concept_3
        207450,  # pickerdramanode_freelancer_artist_forgery
        207531,  # pickerdramanode_freelancer_artist_forgery_2
        207532,  # pickerdramanode_freelancer_artist_forgery_3
        207452,  # pickerdramanode_freelancer_artist_icons
        207534,  # pickerdramanode_freelancer_artist_icons_2
        207451,  # pickerdramanode_freelancer_artist_logo_design
        207537,  # pickerdramanode_freelancer_artist_logo_design_2
        207538,  # pickerdramanode_freelancer_artist_logo_design_3
        207448,  # pickerdramanode_freelancer_artist_portrait
        207540,  # pickerdramanode_freelancer_artist_portrait_2
        207541,  # pickerdramanode_freelancer_artist_portrait_3
        207445,  # pickerdramanode_freelancer_artist_public_artist
        207543,  # pickerdramanode_freelancer_artist_public_artist_2
        207544,  # pickerdramanode_freelancer_artist_public_artist_3
        206612,  # pickerdramanode_freelancer_artist_sketch_artist
        207483,  # pickerdramanode_freelancer_artist_sketch_artist_2
        207484,  # pickerdramanode_freelancer_artist_sketch_artist_3
        207449,  # pickerdramanode_freelancer_artist_splash_art
        207546,  # pickerdramanode_freelancer_artist_splash_art_2
        207547,  # pickerdramanode_freelancer_artist_splash_art_3
        231248,  # pickerdramanode_freelancer_batuu_firstorder_1
        239886,  # pickerdramanode_freelancer_batuu_firstorder_8
        239926,  # pickerdramanode_freelancer_batuu_firstorder_9
        239631,  # pickerdramanode_freelancer_batuu_firstorder_intro_mission
        244214,  # pickerdramanode_freelancer_batuu_firstorder_repeatable_02
        244215,  # pickerdramanode_freelancer_batuu_firstorder_repeatable_03
        244702,  # pickerdramanode_freelancer_batuu_firstorder_repeatable_05
        244458,  # pickerdramanode_freelancer_batuu_firstorder_repeatable_13
        239622,  # pickerdramanode_freelancer_batuu_firstorder_story_mission_1
        239862,  # pickerdramanode_freelancer_batuu_firstorder_story_mission_2
        241102,  # pickerdramanode_freelancer_batuu_firstorder_story_mission_3
        241252,  # pickerdramanode_freelancer_batuu_firstorder_story_mission_4
        241370,  # pickerdramanode_freelancer_batuu_firstorder_story_mission_5
        241543,  # pickerdramanode_freelancer_batuu_firstorder_story_mission_6
        241681,  # pickerdramanode_freelancer_batuu_firstorder_story_mission_7
        242085,  # pickerdramanode_freelancer_batuu_firstorder_story_mission_8
        243713,  # pickerdramanode_freelancer_batuu_neutral_repeatable_mission_02
        237670,  # pickerdramanode_freelancer_batuu_resistance_repeatable_01
        244018,  # pickerdramanode_freelancer_batuu_resistance_repeatable_02
        239414,  # pickerdramanode_freelancer_batuu_resistance_repeatable_05
        245159,  # pickerdramanode_freelancer_batuu_resistance_repeatable_07
        244347,  # pickerdramanode_freelancer_batuu_resistance_repeatable_13
        239468,  # pickerdramanode_freelancer_batuu_resistance_repeatable_15
        243867,  # pickerdramanode_freelancer_batuu_resistance_repeatable_8
        237711,  # pickerdramanode_freelancer_batuu_resistance_story_01
        239231,  # pickerdramanode_freelancer_batuu_resistance_story_02
        241945,  # pickerdramanode_freelancer_batuu_resistance_story_03
        241946,  # pickerdramanode_freelancer_batuu_resistance_story_04
        241948,  # pickerdramanode_freelancer_batuu_resistance_story_06
        241949,  # pickerdramanode_freelancer_batuu_resistance_story_07
        241950,  # pickerdramanode_freelancer_batuu_resistance_story_08
        241951,  # pickerdramanode_freelancer_batuu_resistance_story_09
        244025,  # pickerdramanode_freelancer_batuu_scoundrel_10
        243876,  # pickerdramanode_freelancer_batuu_scoundrel_15
        240205,  # pickerdramanode_freelancer_batuu_scoundrel_3
        243915,  # pickerdramanode_freelancer_batuu_scoundrel_4
        244407,  # pickerdramanode_freelancer_batuu_scoundrel_6
        244384,  # pickerdramanode_freelancer_batuu_scoundrel_8
        244137,  # pickerdramanode_freelancer_batuu_scoundrel_9
        239251,  # pickerdramanode_freelancer_batuu_scoundrel_story_01
        239706,  # pickerdramanode_freelancer_batuu_scoundrel_story_02
        241927,  # pickerdramanode_freelancer_batuu_scoundrel_story_03
        241928,  # pickerdramanode_freelancer_batuu_scoundrel_story_04
        241930,  # pickerdramanode_freelancer_batuu_scoundrel_story_06
        241931,  # pickerdramanode_freelancer_batuu_scoundrel_story_07
        241932,  # pickerdramanode_freelancer_batuu_scoundrel_story_08
        241933,  # pickerdramanode_freelancer_batuu_scoundrel_story_09
        241934,  # pickerdramanode_freelancer_batuu_scoundrel_story_10
        216020,  # pickerdramanode_freelancer_fashion_photographer_athletic_wear
        219711,  # pickerdramanode_freelancer_fashion_photographer_athletic_wear_2
        216073,  # pickerdramanode_freelancer_fashion_photographer_backgrounds
        219799,  # pickerdramanode_freelancer_fashion_photographer_backgrounds_2
        216021,  # pickerdramanode_freelancer_fashion_photographer_everyday_wear
        216022,  # pickerdramanode_freelancer_fashion_photographer_formal_wear
        219720,  # pickerdramanode_freelancer_fashion_photographer_formal_wear_2
        219737,  # pickerdramanode_freelancer_fashion_photographer_formal_wear_3
        216074,  # pickerdramanode_freelancer_fashion_photographer_lights
        219800,  # pickerdramanode_freelancer_fashion_photographer_lights_2
        214795,  # pickerdramanode_freelancer_fashion_photographer_outdoor_wear
        216146,  # pickerdramanode_freelancer_fashion_photographer_outdoor_wear_2
        216075,  # pickerdramanode_freelancer_fashion_photographer_poses
        219738,  # pickerdramanode_freelancer_fashion_photographer_poses_2
        219773,  # pickerdramanode_freelancer_fashion_photographer_poses_3
        214869,  # pickerdramanode_freelancer_fashion_photographer_sleep_wear
        216156,  # pickerdramanode_freelancer_fashion_photographer_sleep_wear_2
        216076,  # pickerdramanode_freelancer_fashion_photographer_style
        222022,  # pickerdramanode_freelancer_fashion_photographer_style_2
        222023,  # pickerdramanode_freelancer_fashion_photographer_style_3
        216023,  # pickerdramanode_freelancer_fashion_photographer_swim_wear
        219728,  # pickerdramanode_freelancer_fashion_photographer_swim_wear_2
        234046,  # pickerdramanode_freelancer_maker_carvedcandle_01
        234047,  # pickerdramanode_freelancer_maker_carvedcandle_02
        234048,  # pickerdramanode_freelancer_maker_carvedcandle_03
        234054,  # pickerdramanode_freelancer_maker_craftedcandle_01
        234055,  # pickerdramanode_freelancer_maker_craftedcandle_02
        234056,  # pickerdramanode_freelancer_maker_craftedcandle_03
        234058,  # pickerdramanode_freelancer_maker_finewalldecor_01
        234059,  # pickerdramanode_freelancer_maker_finewalldecor_02
        234060,  # pickerdramanode_freelancer_maker_finewalldecor_03
        234042,  # pickerdramanode_freelancer_maker_floorlight_01
        234043,  # pickerdramanode_freelancer_maker_floorlight_02
        234044,  # pickerdramanode_freelancer_maker_floorlight_03
        234024,  # pickerdramanode_freelancer_maker_jarcandles_01
        234027,  # pickerdramanode_freelancer_maker_jarcandles_02
        234029,  # pickerdramanode_freelancer_maker_jarcandles_03
        234050,  # pickerdramanode_freelancer_maker_kidbed_01
        234051,  # pickerdramanode_freelancer_maker_kidbed_02
        234052,  # pickerdramanode_freelancer_maker_kidbed_03
        234038,  # pickerdramanode_freelancer_maker_kombucha_01
        234039,  # pickerdramanode_freelancer_maker_kombucha_02
        234040,  # pickerdramanode_freelancer_maker_kombucha_03
        232843,  # pickerdramanode_freelancer_maker_rug_01
        233382,  # pickerdramanode_freelancer_maker_rug_02
        233383,  # pickerdramanode_freelancer_maker_rug_03
        234033,  # pickerdramanode_freelancer_maker_sofa_01
        234034,  # pickerdramanode_freelancer_maker_sofa_02
        234035,  # pickerdramanode_freelancer_maker_sofa_03
        233891,  # pickerdramanode_freelancer_maker_tofizz_01
        234021,  # pickerdramanode_freelancer_maker_tofizz_02
        234022,  # pickerdramanode_freelancer_maker_tofizz_03
        253296,  # pickerdramanode_freelancer_paranormalinvestigator_1easy
        254898,  # pickerdramanode_freelancer_paranormalinvestigator_2medium
        254899,  # pickerdramanode_freelancer_paranormalinvestigator_3hard
        207656,  # pickerdramanode_freelancer_programmer_computer_game
        207981,  # pickerdramanode_freelancer_programmer_computer_game_2
        207982,  # pickerdramanode_freelancer_programmer_computer_game_3
        207980,  # pickerdramanode_freelancer_programmer_computer_game_4
        207983,  # pickerdramanode_freelancer_programmer_computer_game_5
        207657,  # pickerdramanode_freelancer_programmer_encryption
        207987,  # pickerdramanode_freelancer_programmer_encryption_2
        207985,  # pickerdramanode_freelancer_programmer_encryption_3
        207986,  # pickerdramanode_freelancer_programmer_encryption_4
        207658,  # pickerdramanode_freelancer_programmer_hack_listerv
        207990,  # pickerdramanode_freelancer_programmer_hack_listerv_2
        207991,  # pickerdramanode_freelancer_programmer_hack_listerv_3
        207661,  # pickerdramanode_freelancer_programmer_hack_nssa
        207659,  # pickerdramanode_freelancer_programmer_hack_server_system
        207993,  # pickerdramanode_freelancer_programmer_hack_server_system_2
        207655,  # pickerdramanode_freelancer_programmer_mobile_app
        207975,  # pickerdramanode_freelancer_programmer_mobile_app_2
        207976,  # pickerdramanode_freelancer_programmer_mobile_app_3
        207977,  # pickerdramanode_freelancer_programmer_mobile_app_4
        207651,  # pickerdramanode_freelancer_programmer_mod_game
        207966,  # pickerdramanode_freelancer_programmer_mod_game_2
        207648,  # pickerdramanode_freelancer_programmer_spreadsheet_setup
        208760,  # pickerdramanode_freelancer_programmer_spreadsheet_setup_2
        207653,  # pickerdramanode_freelancer_programmer_virus
        207969,  # pickerdramanode_freelancer_programmer_virus_2
        207970,  # pickerdramanode_freelancer_programmer_virus_3
        207654,  # pickerdramanode_freelancer_programmer_website
        207972,  # pickerdramanode_freelancer_programmer_website_2
        207973,  # pickerdramanode_freelancer_programmer_website_3
        207799,  # pickerdramanode_freelancer_writer_biography
        208055,  # pickerdramanode_freelancer_writer_biography_2
        207793,  # pickerdramanode_freelancer_writer_childrens_book
        208039,  # pickerdramanode_freelancer_writer_childrens_book_2
        207792,  # pickerdramanode_freelancer_writer_clickbait_article
        208035,  # pickerdramanode_freelancer_writer_clickbait_article_2
        208036,  # pickerdramanode_freelancer_writer_clickbait_article_3
        208037,  # pickerdramanode_freelancer_writer_clickbait_article_4
        207796,  # pickerdramanode_freelancer_writer_fantasy
        208047,  # pickerdramanode_freelancer_writer_fantasy_2
        207791,  # pickerdramanode_freelancer_writer_marketing_copy
        208033,  # pickerdramanode_freelancer_writer_marketing_copy_2
        208032,  # pickerdramanode_freelancer_writer_marketing_copy_3
        208031,  # pickerdramanode_freelancer_writer_marketing_copy_4
        207794,  # pickerdramanode_freelancer_writer_motivational_book
        208041,  # pickerdramanode_freelancer_writer_motivational_book_2
        207798,  # pickerdramanode_freelancer_writer_mystery
        208052,  # pickerdramanode_freelancer_writer_mystery_2
        208053,  # pickerdramanode_freelancer_writer_mystery_3
        207795,  # pickerdramanode_freelancer_writer_non_fiction
        208043,  # pickerdramanode_freelancer_writer_non_fiction_2
        208044,  # pickerdramanode_freelancer_writer_non_fiction_3
        208045,  # pickerdramanode_freelancer_writer_non_fiction_4
        207790,  # pickerdramanode_freelancer_writer_proofreading
        208028,  # pickerdramanode_freelancer_writer_proofreading_2
        208029,  # pickerdramanode_freelancer_writer_proofreading_3
        207797,  # pickerdramanode_freelancer_writer_science_fiction
        208049,  # pickerdramanode_freelancer_writer_science_fiction_2
        208050,  # pickerdramanode_freelancer_writer_science_fiction_3
        211456,  # pickerdramanode_oddjob_bartend
        209008,  # pickerdramanode_oddjob_beachcomb_seashells
        209009,  # pickerdramanode_oddjob_beachcomb_trash
        209018,  # pickerdramanode_oddjob_beachmenace
        211457,  # pickerdramanode_oddjob_bonsai
        209019,  # pickerdramanode_oddjob_catchfrogs
        209010,  # pickerdramanode_oddjob_cave
        209011,  # pickerdramanode_oddjob_coconut
        211466,  # pickerdramanode_oddjob_datingguru
        211467,  # pickerdramanode_oddjob_divinginstructor
        211276,  # pickerdramanode_oddjob_fooddelivery
        211468,  # pickerdramanode_oddjob_furnitureinstalling
        211469,  # pickerdramanode_oddjob_furnituremoving
        211470,  # pickerdramanode_oddjob_gaming
        211471,  # pickerdramanode_oddjob_hiking
        211472,  # pickerdramanode_oddjob_judge
        209012,  # pickerdramanode_oddjob_kaluapork
        209013,  # pickerdramanode_oddjob_kava
        211433,  # pickerdramanode_oddjob_lawnmowing
        209014,  # pickerdramanode_oddjob_mahimahi
        209015,  # pickerdramanode_oddjob_naturepictures
        211473,  # pickerdramanode_oddjob_packing
        211458,  # pickerdramanode_oddjob_portrait
        211459,  # pickerdramanode_oddjob_seajet
        211460,  # pickerdramanode_oddjob_steal
        211461,  # pickerdramanode_oddjob_stormrepairs
        209016,  # pickerdramanode_oddjob_treasure
        211462,  # pickerdramanode_oddjob_treasurecleaning
        211463,  # pickerdramanode_oddjob_underwaterpictures
        211464,  # pickerdramanode_oddjob_wedding
        211465,  # pickerdramanode_oddjob_wingman
        209017,  # pickerdramanode_oddjob_woodworking
        262229,  # pickerdramanode_villagerhelp_agathacrumplebottom_1
        260890,  # pickerdramanode_villagerhelp_agnescrumplebottom_1
        262230,  # pickerdramanode_villagerhelp_crittertender
        262502,  # pickerdramanode_villagerhelp_foodforage_short_crittertender
        262501,  # pickerdramanode_villagerhelp_foodforage_short_groceryowner
        262503,  # pickerdramanode_villagerhelp_foodforage_short_pubowner
        262491,  # pickerdramanode_villagerhelp_gardenshort_agathacrumplebottom
        262490,  # pickerdramanode_villagerhelp_gardenshort_agnescrumplebottom
        262231,  # pickerdramanode_villagerhelp_grocerydelivery
        262232,  # pickerdramanode_villagerhelp_groceryowner
        263186,  # pickerdramanode_villagerhelp_livestockgardenlong_agathacrumplebottom
        263187,  # pickerdramanode_villagerhelp_livestockgardenlong_agnescrumplebottom
        263189,  # pickerdramanode_villagerhelp_livestockgardenlong_grocerydelivery
        263188,  # pickerdramanode_villagerhelp_livestockgardenlong_groceryowner
        268047,  # pickerdramanode_villagerhelp_livestockgardenlong_mayor
        262485,  # pickerdramanode_villagerhelp_livestockshort_grocerydelivery
        262484,  # pickerdramanode_villagerhelp_livestockshort_groceryowner
        262233,  # pickerdramanode_villagerhelp_mayor
        263015,  # pickerdramanode_villagerhelp_narrative_agathacrumplebottom_2
        263016,  # pickerdramanode_villagerhelp_narrative_agnescrumplebottom_2
        262234,  # pickerdramanode_villagerhelp_pubowner
        268121,  # pickerdramanode_villagerhelp_socialmedium_agathacrumplebottom
        268120,  # pickerdramanode_villagerhelp_socialmedium_agnescrumplebottom
        263200,  # pickerdramanode_villagerhelp_socialmedium_grocerydelivery
        263202,  # pickerdramanode_villagerhelp_socialmedium_mayor
        263201,  # pickerdramanode_villagerhelp_socialmedium_pubowner
        261504,  # pickerdramanode_villagerhelp_socialshort_grocerydelivery
        261265,  # pickerdramanode_villagerhelp_socialshort_mayor
        261505,  # pickerdramanode_villagerhelp_socialshort_pubowner
        263204,  # pickerdramanode_villagerhelp_wildanimalfoodlong_crittertender
        262492,  # pickerdramanode_villagerhelp_wildanimalshort_crittertender
        182428,  # playerplanneddramanode
        310173,  # playerplannedstayoverdramanode
        276073,  # playerplannedweddingdramanode
        280767,  # preprominvitedramanode
        280737,  # prominvitedramanode_hsprom
        195420,  # runaffordancedramanode_actorcareer_agency_estellegable_offergig
        198710,  # runaffordancedramanode_actorcareer_agency_estellegable_offergig_tutorial
        195417,  # runaffordancedramanode_actorcareer_agency_hangten_offergig
        198711,  # runaffordancedramanode_actorcareer_agency_hangten_offergig_tutorial
        195418,  # runaffordancedramanode_actorcareer_agency_seriousbusiness_offergig
        198712,  # runaffordancedramanode_actorcareer_agency_seriousbusiness_offergig_tutorial
        195397,  # runaffordancedramanode_actorcareer_agency_wearereallyhuman_offergig
        198713,  # runaffordancedramanode_actorcareer_agency_wearereallyhuman_offergig_tutorial
        194462,  # runaffordancedramanode_actorcareer_auditions_commercial_hospital
        194461,  # runaffordancedramanode_actorcareer_auditions_commercial_housenice
        194463,  # runaffordancedramanode_actorcareer_auditions_commercial_kids
        193028,  # runaffordancedramanode_actorcareer_auditions_commercial_pirate
        194464,  # runaffordancedramanode_actorcareer_auditions_commercial_western
        194466,  # runaffordancedramanode_actorcareer_auditions_movie_city
        194467,  # runaffordancedramanode_actorcareer_auditions_movie_medieval
        194468,  # runaffordancedramanode_actorcareer_auditions_movie_pirate
        194469,  # runaffordancedramanode_actorcareer_auditions_movie_superhero
        194470,  # runaffordancedramanode_actorcareer_auditions_movie_victorian
        194465,  # runaffordancedramanode_actorcareer_auditions_movie_western
        194475,  # runaffordancedramanode_actorcareer_auditions_tvhigh_apocalypse
        194473,  # runaffordancedramanode_actorcareer_auditions_tvhigh_hospital
        194474,  # runaffordancedramanode_actorcareer_auditions_tvhigh_police
        194472,  # runaffordancedramanode_actorcareer_auditions_tvhigh_victorian
        194471,  # runaffordancedramanode_actorcareer_auditions_tvhigh_western
        194477,  # runaffordancedramanode_actorcareer_auditions_tvlow_houselow
        194479,  # runaffordancedramanode_actorcareer_auditions_tvlow_housenice
        194476,  # runaffordancedramanode_actorcareer_auditions_tvlow_kids
        194478,  # runaffordancedramanode_actorcareer_auditions_tvlow_pirate
        194480,  # runaffordancedramanode_actorcareer_auditions_tvlow_western
        210099,  # runaffordancedramanode_freelancer_offergig_artist
        214837,  # runaffordancedramanode_freelancer_offergig_fashion_photographer
        257960,  # runaffordancedramanode_freelancer_offergig_interiordecorator
        234250,  # runaffordancedramanode_freelancer_offergig_maker
        210100,  # runaffordancedramanode_freelancer_offergig_programmer
        210098,  # runaffordancedramanode_freelancer_offergig_writer
        124702,  # runaffordancedramanode_phone_chat
        164723,  # runaffordancedramanode_phone_chat_acquiredfamilyrelbit
        316136,  # runaffordancedramanode_phone_chattycall
        193812,  # runaffordancedramanode_phone_feudbringer_discussfeud
        199061,  # situation_dramanode_famevisit
        235084,  # situationdramanode_civicinspector
        222417,  # situationdramanode_collegeorganization_secretsociety_joinvisit
        233685,  # situationdramanode_communitycloseness_birthdaygift
        233681,  # situationdramanode_communitycloseness_complaint_despised
        234416,  # situationdramanode_communitycloseness_complaint_ecomaster
        235004,  # situationdramanode_communitycloseness_complaint_followup
        233682,  # situationdramanode_communitycloseness_handyneighbor
        237855,  # situationdramanode_communitycloseness_introtocivicpolicies
        233684,  # situationdramanode_communitycloseness_randomgift
        235567,  # situationdramanode_communitycloseness_randomgift_championofthepeople
        239187,  # situationdramanode_communitycloseness_randomgift_makernpc
        233683,  # situationdramanode_communitycloseness_sparerecyclings
        233686,  # situationdramanode_communitycloseness_trashhelp
        317780,  # situationdramanode_familytrope_sundayvisit
        208406,  # situationdramanode_islanderculture_deathcomfort
        208991,  # situationdramanode_islanderculture_extrafood
        208992,  # situationdramanode_islanderculture_needsomethingfixed
        278850,  # situationdramanode_npcrelationshipautonomy_asktobe_bestfriend
        278851,  # situationdramanode_npcrelationshipautonomy_asktobe_boyfriendgirlfriend
        278852,  # situationdramanode_npcrelationshipautonomy_asktoprom
        278853,  # situationdramanode_npcrelationshipautonomy_asktoprom_asfriends
        278854,  # situationdramanode_npcrelationshipautonomy_breakupwith
        278855,  # situationdramanode_npcrelationshipautonomy_propose
        224401,  # situationdramanode_repo_situation
        235712,  # situationdramanode_repo_situation_billsdelinquent
        221714,  # situationdramanode_roommatenpc_argument
        221715,  # situationdramanode_roommatenpc_gethype
        223264,  # situationdramanode_roommatenpc_lockedout
        221716,  # situationdramanode_roommatenpc_whispers
        221717,  # situationdramanode_roommatenpc_wooing
        199107,  # situationdramanode_roommatevisit
        188849,  # situationdramanode_scarecrow
        191047,  # situationdramanode_scarecrow_purple
        191046,  # situationdramanode_scarecrow_red
        296149,  # situationdramanode_scenario_onboarding_newintown_phase4_acquaintedvisitor_1
        297386,  # situationdramanode_scenario_onboarding_newintown_phase4_acquaintedvisitor_2
        297847,  # situationdramanode_scenario_onboarding_stuckintheirshadow_friendvisit
        301778,  # situationdramanode_scenario_onboarding_stuckintheirshadow_lastinvite
        297845,  # situationdramanode_scenario_onboarding_stuckintheirshadow_rivalvisit
        235042,  # situationdramanode_trashupdate_wastemanager
        225717,  # situationdramanode_universitygraduation_arts
        225718,  # situationdramanode_universitygraduation_science
        154176,  # situationdramanode_vampire_homeinvasion
        308501,  # stayoverdramanode_clone
        311526,  # stayoverdramanode_couchsurf
        309230,  # stayoverdramanode_couchsurf_kyle
        309234,  # stayoverdramanode_disaster
        309232,  # stayoverdramanode_friend
        309235,  # stayoverdramanode_householdloss
        321829,  # stayoverdramanode_infantintro
        309233,  # stayoverdramanode_mopeyvisit
        309231,  # stayoverdramanode_parentalhelp
        182316,  # test_holidaydramanode
        198060,  # tutorialdramanode
        281000,  # venueeventdramanode_thriftstore_fashion_friday
        279012,  # venueeventdramanode_thriftstore_fashion_monday
        279014,  # venueeventdramanode_thriftstore_openmic_comedy
        279011,  # venueeventdramanode_thriftstore_openmic_poetry
        226220,  # venueeventdramanode_university_studentcommons_arts_debatepractice_tues
        227820,  # venueeventdramanode_university_studentcommons_arts_debatepractice_wed
        222193,  # venueeventdramanode_university_studentcommons_arts_examcram
        222042,  # venueeventdramanode_university_studentcommons_arts_mixer
        221593,  # venueeventdramanode_university_studentcommons_arts_poetry
        221592,  # venueeventdramanode_university_studentcommons_science_esports
        222226,  # venueeventdramanode_university_studentcommons_science_examcram
        222057,  # venueeventdramanode_university_studentcommons_science_mixer
        226976,  # venueeventdramanode_university_studentcommons_science_robotbuilding_thursday
        227056,  # venueeventdramanode_university_studentcommons_science_robotbuilding_tuesday
    )


log = BBLogRegistry().register_log(ModIdentity(), 'bbs_drama_node_disabler')
log.enable()


@BBInjectionUtils.inject(ModIdentity(), BaseDramaNode, BaseDramaNode._test.__name__)
def _bbs_disable_drama_nodes(original, self, *_, **__) -> TestResult:
    drama_node_id = getattr(self, 'guid64')
    if drama_node_id in BBDramaNodeDisabler.DISABLED_DRAMA_NODE_IDS:
        log.debug('Preventing BaseDramaNode Drama Node from starting.', drama_node=self, drama_node_id=drama_node_id)
        return False
    return original(self, *_, **__)
