"""
This mod is licensed under the Creative Commons Attribution 4.0 International public license (CC BY 4.0).
https://creativecommons.org/licenses/by/4.0/
https://creativecommons.org/licenses/by/4.0/legalcode

Copyright (c) BLUUBERRYBONANZA
"""
from bluuberrylibrary.enums.classes.bb_int_flags import BBIntFlags


class BBSSettlementMemberJobFlags(BBIntFlags):
    NONE: 'BBSSettlementMemberJobFlags' = ...
    COOK: 'BBSSettlementMemberJobFlags' = ...
    NANNY: 'BBSSettlementMemberJobFlags' = ...
    GARDENER: 'BBSSettlementMemberJobFlags' = ...
    GUARD: 'BBSSettlementMemberJobFlags' = ...
    DOCTOR: 'BBSSettlementMemberJobFlags' = ...
    SCOUT: 'BBSSettlementMemberJobFlags' = ...
    SANITATION: 'BBSSettlementMemberJobFlags' = ...
    MAINTENANCE: 'BBSSettlementMemberJobFlags' = ...
    TEACHER: 'BBSSettlementMemberJobFlags' = ...
    GATHERER: 'BBSSettlementMemberJobFlags' = ...

    @classmethod
    def get_display_name(cls, value: 'BBSSettlementMemberJobFlags') -> int:
        return 0

    @classmethod
    def get_display_description(cls, value: 'BBSSettlementMemberJobFlags') -> int:
        return 0
